### ISSUE TITLE
Trac: #367 --disable-elements=all, --enable-elements=XXX,YYY,ZZZ

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#10]
It would be nice to be able to select which element libraries are built at .configure time. While one can put a .ignore file in each element library directory, it would be nice to have configure arguments like: 

```
.configure --disable-elements=all --enable-elements=Merlin,MemHierarchy
```

Which would only enable those two Element Libraries. It would also be an error if a user specifically requested an element library which was unable to configure itself. ie, request Ariel, but PIN wasn't found.

**Comment by allevin** [comment]
Comment by bjmoor:

In 10003:

Add a '--disable-elements' to configure option.
This will build the core only.

See: #367

**Comment by bjmoor** [comment]
I believe this issue belongs in sst-elements, rather than core, as the core no longer builds any elements.
