### ISSUE TITLE
SST Python Scripts need mechanism to set thread count

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#100]
Neef a setThreadCount in Python for cases where threading shouldn't happen (components are known not to be thread safe).

**Comment by bjmoor** [comment]
Any such call should be max-limited to what the user specified via -n on the commandline.

For the use-case above, checking getThreadCount() and exiting with an error is probably a better solution.

**Comment by nmhamster** [comment]
I agree on the max limit. Hmmm on not setting it down.

Also, what happens if I have 16 threads and only 2 components, at one point I think that was breaking?



Si Hammond

Scalable Computer Architectures
Center for Computing Research
Sandia National Laboratories, NM, USA
[Sent from Good, please excuse typos]
________________________________

**Comment by bjmoor** [comment]
> Also, what happens if I have 16 threads and only 2 components, at one point I think that was breaking?

Since early on, SST detects that there are no components assigned to thread-ranks, and removes them from the simulation.  If that is not working, that is an issue which should be raised.

**Comment by bjmoor** [comment]
Didn't mean to close, just comment.
