### ISSUE TITLE
Python 3.12 fixes needed

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-core#1002]
Python 3.12 compiles with sst-core but there are some compile warnings and test warnings/failures.
* Compile warnings related to changes in cpython
* Warnings about invalid escape sequences in test frameworks and input files
  * sst_unittest_support.py use of "\w" in a regex
  * test_UnitAlgebra prints a "\=" which is interpreted as an attempted escape sequence and warns, causing the test output to diff

sst-elements compiles but have not yet tried tests. Probably some similar issues.

**Comment by feldergast** [comment]
With 3.12, the element library python modules do not seem to load correctly.  For now, we won't be able to support python 3.12 for any element library that has python modules.

**Comment by berquist** [comment]
This is the core reason why elements tests fail on Ubuntu 24.04, because they ship Python 3.12.

**Comment by berquist** [comment]
Fixed in https://github.com/sstsimulator/sst-core/pull/1073
