### ISSUE TITLE
Help needed on memory allocation/release scheme for Events

### ISSUE THREAD

**Issue by zhwu95** [sstsimulator/sst-core#1016]
New help request for SST Core

----------------------
1 - Detailed description of issue needing support

This is a general question about the assumptions I should make about links and pointers to event.

Suppose I have two component instances `A` and `B`. `A` allocates an `Event` with `new` (e.g. `Event* e = new SomeEvent;`) and sends  the event to `B` (e.g. `link->send(e);`), where `B` would handle this event and release the resources with `delete e` in its link handler.

Now `A` and `B` may or may not reside in the same process.

My first sets of questions are:
1. Is there any guarantee that the addresses of the `Event` seen by `A` and `B` are the same, irrespective of the partitioning of `A` and `B`?
2. Suppose `A` and `B` are in processes 0 and 1 respectively. After `A` calls `link->send(e);`, is the memory allocated for the event in process 0 deallocated, and hence calling `delete e` on `B` ensures no memory leak? If so, who should deallocate the event memory in process 0 - is it me or is it that the sst/mpi runtime handles it?
3. Should I assume that once I call `link->send(e);`, the ownership of  `e` is moved, and hence I should not access the event, even if I have a pointer to it?

Now in a different setup, where `B`, instead of calling `delete e`, sends the event back to `A` through the link.
Again, `A` and `B` may or may not reside in the same process.

My second sets of questions are:

1. Do we have any guarantee that the address of the event received by A is the same as the event sent by A, irrespective of the partitioning of `A` and `B`?

Clarifications are appreciated!

**Comment by feldergast** [comment]
In general, if you are within the same process/MPI rank, even if within different threads, the address of the pointer will be the same in both A and B.  If they are in different processes, then the pointer will be different in A and B (unless by some miracle you accidentally get the same address).  If the event is serialized to send between processes, then the serialization infrastructure will delete the source event.  The APIs were designed such that the Components do not need to know what rank they are on relative to other Components and the core takes care of all the details needed for parallelization.

For #3, you are correct.  Once you send an event, you no longer have ownership of it and should not access it anymore.

For the last question: You are not guaranteed that the event pointer will be the same if A & B reside in different processes. The event will go through the serialization interface (twice in this case), and thus you will get an address different than the one that was sent.

A quick note:  This is how things are coded today.  The SST APIs give no guarantees about the address of the event pointers in any case, so you shouldn't rely on the addresses.  It is safest to never check the address and just access the contents of the event.

**Comment by zhwu95** [comment]
Thanks for the clarification. Now it makes a lot of sense to me.

Closing as solved.
