### ISSUE TITLE
--enable-picky feature is not available in the new external core/elements build system

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-core#104]
On the old build architecture, the configuration option --enable-picky turned on almost all compiler warnings .  

Normally -enable-picky was not enabled by default on the distribution versions of SST.  However, it was enabled if it saw a .svn or .hg directory (i.e. default it on for developer copies of the source code retrieved from subversion). 

This feature does not exist in the current build architecture.  There is some discussion of bringing back in.  This issue is written to raise discussion on the need or desire to re-implement this feature.

For information, here is the --enable-picky code in the configure.ac file from the old build architecture.

C_ARG_ENABLE(picky, 
    AC_HELP_STRING([--enable-picky],
                   [enable developer-level compiler pickyness when building (default: disabled)]))
if test -z "$enable_picky" && test -d .svn -o -d .hg ; then
    echo "--> developer override: enable picky compiler by default"
    enable_picky=yes
fi
...
if test "$enable_picky" = "yes" -a "$GCC" = "yes" ; then
  CFLAGS="$CFLAGS -Wall -Wno-long-long -Wmissing-prototypes -Wstrict-prototypes -Wcomment"
fi

if test "$enable_picky" = "yes" -a "$GXX" = "yes" ; then
  CXXFLAGS="$CXXFLAGS -Wall -Wno-long-long"
fi

**Comment by bjmoor** [comment]
Is this supposed to affect the core, only?  Should it affect anything building with the core?
My initial reaction is that these flags should probably be enabled by default for the core.
