### ISSUE TITLE
Trac: #400 Configure check for PIN should abort if too old of a version is found

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#11]
When I .configure using --with-pin=${INTEL_PIN_DIRECTORY} and the directory which I point to contains a version of PIN which is too old to work with the current SST, an error should occur, rather than blind acceptance. It is not nice to have configure work, but then make fail with a very non-obvious compilation error (missing header files).

**Comment by allevin** [comment]
Moved to 6.0.0 and will be looked at as part of element break out.

**Comment by allevin** [comment]
Transferred to [issue 404 on sst-elements](https://github.com/sstsimulator/sst-elements/issues/404)
