### ISSUE TITLE
sstsimulator_conf_get_value_bool broken

### ISSUE THREAD

**Issue by freund** [sstsimulator/sst-core#1120]
New issue for sst-core
----------------------
1. _Detailed description of problem_
The function `sstsimulator_conf_get_value_bool` of the `sst_unittest_support` Python module is broken. It mistakenly calls `getbool` instead of `getboolean` from the class `RawConfigParser` of Python's `configparser` library, so `sstsimulator_conf_get_value_bool` causes an AttributeError to be thrown.

2. _Describe how to reproduce the issue_
Write a test with `from sst_unittest_support import *` and try to use `sstsimulator_conf_get_value_bool` to get a value from the SST configuration file.

4. _What operating system and versions_
I'm using TOSS 4.8-2.

6. _What versions of external libraries (MPI, etc.)_
I'm using Python 3.12.5. Maybe `getbool` worked with an older Python release, but I can't find any evidence of that.

8. _Provide sha1 of all relevant SST repositories (sst-core, sst-elements, etc.)_
`sst-core c13aff968e9684ceab0f2b50e0887c08091956cd`

**Comment by berquist** [comment]
Fixed by https://github.com/sstsimulator/sst-core/pull/1121
