### ISSUE TITLE
Question: Are `SST::Component` implementers called in a thread safe manner?

### ISSUE THREAD

**Issue by Dherse** [sstsimulator/sst-core#1166]
Does SST synchronize mutable accesses to an `SST::Component`?
----------------------
My question is whether it can be assumed, within the implementation of a custom component, that it is being called mutably only once at the same time? Or can there be multiple simultaneous mutable calls, potentially causing UB, due to say a link and a clock triggering their handlers at the same time?

As an aside, it could be nice opening a GitHub discussions page (like https://github.com/typst/typst/discussions) to avoid having issues that are just questions. Or if there is a more appropriate place to ask questions I do no know about, please let me know :)

**Comment by feldergast** [comment]
A Component is assigned to a single thread, so there can only be one event active on a Component at any given time.  The design of SST core aims to hide all parallelization from Components. One additional consequence of this is that Components should not use static data members as there is no guarantee all Components of a given type will be on the same rank.
