### ISSUE TITLE
Add [[noreturn]] attribute to SST::Output::fatal()

### ISSUE THREAD

**Issue by leekillough** [sstsimulator/sst-core#1169]
**Describe the solution you'd like**
Add `[[noreturn]]` attribute to `SST::Output::fatal()`

`[[noreturn]]` allows greater optimization and avoids warnings about missing return values in functions which call `SST::Output::fatal()` but don't `return` values.

**Describe alternatives you've considered**
Add dummy `return` after calls to `SST::Output::fatal()` to avoid warnings

**Comment by feldergast** [comment]
I think this makes a lot of sense, but the fatal() function as written is not actually no return.  There are corner cases in threaded runs where two threads calling fatal() at the same time will cause the one that reaches the end of the function last to return (you can't have MPI_abort()/exit() called more than once).  If you'd like to put in a PR to add the attribute, then you'll probably need to throw an exception at the end of the function to actually make the function no return.

**Comment by leekillough** [comment]
Speaking of handling race conditions, I don't know if the current code uses `call_once()`, but a fast and simple method is local static initialization (the so-called Meyers Singleton) at the point of exit:

```c++
static int exit_once = (MPI_exit(), 0);
std::terminate();
```

That static initialization can be placed at the point of the exit in any part of a function, and only one thread will call it. If it releases the lock and other threads continue, they will call `std::terminate()`. But it probably will never release the lock before `MPI_exit()` is called and (never) returns.

**Comment by leekillough** [comment]
If there are several places in SST which may call `MPI_exit()`, then the above code can be placed in a wrapper to guard against race conditions, e.g.:
```c++
[[noreturn]] void SST_exit() {
  static int exit_once = (MPI_exit(), 0);
  std::terminate();
}
```
The API can be changed if exiting with a specific exit code needs to be supported.
