### ISSUE TITLE
Trac: #389 Adaptation in stats output format

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#12]
I suggest the following simple change in the .csv format 

1) Divide ComponentName in two columns ComponentName and ComponentId In this way, rtr.0x0x0 would become rtr, 0x0x0. Unless the point is default separator (if yes, this ticket can be deleted but perhaps the point separator concept should be documented), keeping a single column makes parsing the component name hasardous.

**Comment by bjmoor** [comment]
In SST simulations created via Merlin's Topology Generators, router names look like "rtr.0x0x0".  The entire string is the SST Component name.   The '0x0x0' piece of the name is __Merlin's__ convention to aid the user (versus just rtr1, rtr2, rtr3, etc).  The ComponentId is an auto-incrementing number that is typically not user-visible.

To my knowledge, there is no SST-level convention on component names.

**Comment by jjwilke** [comment]
Yes, component ID does not show up in the output. Only the component name passed to
````
sst.Component(name,...)
````
There is an option to pass a sub ID (e.g. port0), which does form another column.

**Comment by jjwilke** [comment]
Related to #381. Any reason not to close this?

@nmhamster 
@bjmoor

**Comment by jjwilke** [comment]
Releated to https://github.com/sstsimulator/sst-core/issues/484

**Comment by allevin** [comment]
Taken over by events - We are closing.
