### ISSUE TITLE
configure --with-zoltan is successful even if zoltan is not found

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-core#130]
When configure is run against the sst-core, if "--with-zoltan" is used, but Zoltan cannot be found the configure will still succeed.  The report at the end does properly reflect that Zoltan is not enabled.  

This may not be a bug, but it may be confusing to the user who expected Zoltan to be part of the core build and did not pay attention to the report at the end of configure.  

Recommend that configure should fail if Zoltan is not found in this situation.

**Comment by allevin** [comment]
Changes in PR #132 did NOT correct the issue.

**Comment by nmhamster** [comment]
@allevin - additional change set in "Fix issue with Zoltan configure where --with-zoltan supplied by is empty string #137". You found an additional error case.

**Comment by allevin** [comment]
Verified that if zoltan not found, configure will fail.
