### ISSUE TITLE
serialization for raw_ptr_wrapper

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#135]
##### New Issue for sst-core
```
template <class TPtr>
class raw_ptr_wrapper
{
public:
    TPtr*& bufptr;
    raw_ptr_wrapper(TPtr* ptr) :
        bufptr(ptr) {}
};

should be

public:
    TPtr*& bufptr;
    raw_ptr_wrapper(TPtr*& ptr) :
        bufptr(ptr) {}
};
```
pretty sure...

**Comment by jjwilke** [comment]
missing ampersand in ctor, otherwise just binding a reference to a stack variable

**Comment by nmhamster** [comment]
@jjwilke Can you elaborate on what file etc this is in? I have been looking in the `serialize_array.h` file and cannot see the function prototype in the file at all. Thanks.

**Comment by jjwilke** [comment]
serialize_array.h line 47
