### ISSUE TITLE
returning reference to temporary

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#136]
##### New Issue for sst-core

`1` Detailed description of problem or enhancement

Returning an r-value reference to a temporary seems like a bad idea

`2` Describe how to reproduce

`3` What Operating system(s) and versions 

`4` What version of external libraries (Boost, MPI)

`5` Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

`6` Fill out Labels, Milestones, and Assignee fields as best possible
Scott, fix this

Line 121 in elemLoader.cc

static std::vectorstd::string&& splitPath(const std::string & searchPaths)
{
    std::vectorstd::string paths;

The likely behavior is that you just end up with an empty return value and the appearance that SST_LIB_PATH has been ignored. 

This array will never be that big.  Just return a regular value and hope copy elision does its job.

**Comment by bjmoor** [comment]
This is C++11 move semantics, not returning a reference to a local.

**Comment by jjwilke** [comment]
It would be C++11 move semantics if you had moved into another function or another variable before the end of the function.  The destructor of the vector is getting called at the end of the function before it's captured by any move constructor.

It might accidentally work on some systems, but on Mac with Clang and CentOS with gcc you always get an empty array returned by splitPaths, which breaks all our stuff.

**Comment by jjwilke** [comment]
Take 30 seconds to google it

**Comment by bjmoor** [comment]
This should be fixed with @jjwilke commit.
