### ISSUE TITLE
SST-Core should provide man pages

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#139]
SST-Core does not currently provide man pages which makes commands somewhat undocumented.

**Comment by allevin** [comment]
While not man pages, doxygen documentation on sst-core can be created.  Additionally the doxygen output will be made available on the sst-simulator.org website.  

We are investigating methods of publishing on the website the documentation against the master (or maybe devel) branch when the overnight testing passes.  We would then have the docs for the last release and the latest clean build.

**Comment by allevin** [comment]
We are working on other documentation for core, man pages will not be supported. - Closing
