### ISSUE TITLE
Trac: #431 Connector for Components/Modules written in Python

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#14]
Use case from ISCA tutorial, would like to be able to prototype components in Python and have them connect to SST simulations (which may use non-Python components). Requires connector from C++ classes to Python, issues with Python interpreter per component etc

**Comment by bjmoor** [comment]
The 'pyproto' element library attempts to address this issue.   Translation of generic events between Python and C++ is probably unsolvable in the near term.

**Comment by bjmoor** [comment]
Going to close/archive this issue for now, pending new developments.
