### ISSUE TITLE
Wrong tarball name in installation guide

### ISSUE THREAD

**Issue by cdunham** [sstsimulator/sst-core#148]
Minor issues of file/directory naming only:

http://sst-simulator.org/SSTPages/SSTBuildAndInstall6dot0dot0SeriesDetailedBuildInstructions/
refers to sst-core-6.0.tar.gz
when it is in fact sstcore-6.0.0.tar.gz
also for sst elements.

When extracted, the directories are "sstcore-6.0.0" and "sst-elements-library-6.0.0" respectively.  The documentation shows favoritism to the hyphenated version but the distributions tend to not have them.

**Comment by allevin** [comment]
Corrected documentation for 6.0 and 6.1 to properly reflect correct tarball names for core, elements and macro.
