### ISSUE TITLE
Trac: #433 SST auto connect to debug on signal?

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#15]
Use case from ISCA, can we automatically connect to a debugger when a terminate signal is received Would be a good outcome for long running simulation.

**Comment by bjmoor** [comment]
My initial reaction is that this is going to be very platform specific.  Can you point to other projects that have done this, so that we may learn how it can be accomplished?

**Comment by allevin** [comment]
Will not implement - closed
