### ISSUE TITLE
C++11 override correctness for virtual functions

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#153]

**Comment by nmhamster** [comment]
@jjwilke do we know if this works across all of our supported compiler platforms yet? I don't know but we could test some of this out if you liked?

**Comment by jjwilke** [comment]
It's supported in all compilers as part of the C++11 standard. Scott and I discussed via e-mail exchange, copied below.  I think we figured out this would be easier to just provide another set of serialization macros that allows us to get rid of the compiler warnings since macro is the only element library worried about override correctness.

One possibility is to have two sets of serialization macros that go through a common base to avoid code replication.  One is override-correct for those who care (basically just me at this point). One is not for those who don’t.

#define ImplementSerializableBase(cls, overKeyword)

#define ImplementSerializable(cls) \
ImplementSerializableBase(cls,) //omits the override keyword - no warnings generated for those not using override correctness
#define ImplementSerializableOverride(cls) \
ImplementSerializableBase(cls,override) //includes the override keyword - no warnings generated for those using override correctness

**Comment by nmhamster** [comment]
Moved to SST 7.0 because we still need to support older compilers.

**Comment by bjmoor** [comment]
Looks like 'override' was enabled in GCC 4.7.   https://gcc.gnu.org/projects/cxx-status.html#cxx11
According to our release notes, GCC 4.8.2 is our minimal tested configuration.

**Comment by bjmoor** [comment]
@jjwilke Can you describe a little bit more about what exactly you're looking for here?  Since SST 7.0 requires GCC 4.8, I think we should be good to go on adding 'override'.  Where exactly is it needed?

**Comment by jjwilke** [comment]
It's primarily in the serialization macros.  The warning flag is -Winconsistent-missing-override in clang, -Wsuggest-override in gcc >=5.  These get tripped by default whenever the compiler sees the "override" keyword anywhere. SST-macro uses the override keyword everywhere - so building the macro element library spews a ton of warnings about the virtual serialization functions that aren't marked override in serializable.h.

The problem is - if you add override to the serialization functions in the core, you'll have to add override EVERYWHERE in the core and element libraries or you'll start getting the same warnings.  Options are:

1) I can try modify our build system to just add -Wno-inconsistent-missing-override in clang, -Wno-suggest-override in gcc > 5 to CXXFLAGS to turn off the warnings
2) You guys can modify CXXFLAGS in SST core to turn off the warnings (we automatically pick up the same CXXFLAGS). This might be best since it would allow you to gradually add override keywords in core and elements without getting warnings about inconsistent use.
3) Implement two sets of macros as described above with different override qualifiers. No one has to disable any warnings.

**Comment by bjmoor** [comment]
I'm not opposed to "doing it right", and placing `override` keywords throughout the core.   I might then recommend the SST-ELEMENTS Makefiles have `-Wno-suggest-override` / `-Wno-inconsistent-missing-override,` just so that they build cleanly, without forcing people to use `override`.

I'll see how much effort it is, and maybe toss up a branch /PR for discussion.

Thoughts from others?

**Comment by bjmoor** [comment]
@jjwilke Since Si went ahead and merged the PR#225, can you check to see if this has helped at all, and if so, if this issue can go ahead and close?
Thanks!

**Comment by jjwilke** [comment]
Compiles cleanly now. Waiting for PR111 for sst-macro. Then closed on sst-macro end.

**Comment by bjmoor** [comment]
PR 111 from sst-macro merged.   Closing this issue.
