### ISSUE TITLE
Trac: #436 Simple interfaces in the SST Info output

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#17]
Feedback from ISCA tutorial, want to see simple interfaces in the SST info output dump.

**Comment by allevin** [comment]
Additional information: Users wanted to see what Simple Interfaces (inside sst/core/interfaces - simpleMem, simpleNetwork) were implemented by an Element Library. This would require changes to the ElementLibrary Info structures to provide enough information for SST Info to decode.

**Comment by allevin** [comment]
[from bjmoor]
I feel that the "Simple Interfaces" becomes a limitation for this.

ElementInfoModule and ElementInfoSubComponent already have the provides field, which should describe what Class (other than Module and SubComponent) the module inherits from. This effectively provides a mechanism to say what Interface the module provides.

What may be lacking is a standard mechanism for Components (and Sub-Components?) to enumerate what sub-classes they will be looking for modules to implement. Currently, the only real viable option is to document in the parameters that a certain parameter looks to "define the name of a module which implements interface sst.Interfaces.SimpleMem?".

**Comment by bjmoor** [comment]
In line with this Issue title...  The 'sst.*' parititoners, core modules, etc...  Should be findable via sst-info.

**Comment by allevin** [comment]
Supported in new ELI
