### ISSUE TITLE
SST 6.1 claims version 6.0

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#171]
SST 6.1's release did not update the 'configure.ac' file with the updated release version.  As such, SST 6.1 still claims to be SST 6.0.

    $ sst --version
    SST-Core Release Version (6.0.0, Branch SHA: c3e19eecdbb75bc9260048e075d1e7362bf27fe0)
    $ grep AC_INIT configure.ac
    AC_INIT([SSTCore], [6.0.0], [sst@sandia.gov])

**Comment by allevin** [comment]
I just downloaded the release tarballs.  Both core and elements configure.ac show 6.1.  

Are you building from the devel branch?  

We did not change the configure.ac for the devel branch.  The change is made in the pre-release branch.

**Comment by bjmoor** [comment]
Devel and Master branches.
We should probably not have those branches claim a version older than what we release.
Perhaps we should change the version in those branches to something like '6.1.0-dev'?

**Comment by nmhamster** [comment]
@bjmoor we used to have something like "internal" or "devel" in the version area. I guess that got changed somehow. You wouldn't expect to have that show 6.0 or 6.1 would you?

**Comment by bjmoor** [comment]
I guess I would expect to see something that isn't a release.  devel or dev would be suitable.  The Autoconf-specified version shows up, not just in `sst --version`, but also as the `pkg-config` target file.  I was surprised to see a 'SST-6.0.0.pc' file being installed on a recent `make install`, hence this issue report.

**Comment by allevin** [comment]
I am working on this.  How about we use "Under-Development"?  I feel that "devel" is too close to the name of the branch most people work on.  We could use "Internal", but I don't feel that it conveys that the version is in development.  

We have code that will detect if the code has git information and will display it when running sst --version.  If .git directory is not present (for a release or a zipped download of the git repo), the version will still reflect "Under-Development" until we set the actual version the in pre-release branch.

**Comment by allevin** [comment]
Fixed in Pull Request #176
