### ISSUE TITLE
python-config --ldflags may not return -L<directory to library> on some systems

### ISSUE THREAD

**Issue by mjleven** [sstsimulator/sst-core#187]
sst_check_pythong.m4 expects "python-config --ldflags" to return a path to the python library but this may not happen on some systems. 

On a Cray the system python python-config --ldflags returns:
-lpthread -ldl -lutil -lm -lpython2.6

On the same system user build version of python 2.7.6 python-config --ldflags returns:

-lpthread -ldl -lutil -lm -lpython2.7 -Xlinker -export-dynamic

**Comment by bjmoor** [comment]
Seems like this is a known bug in Python.  See https://bugs.python.org/issue7352

A workaround solution would be to check to see if a '-L' is included in the output of `$PYTHON_CONFIG_EXE --ldflags`, and if not, prepend that output with: `"-L$($PYTHON_CONFIG_EXE --exec-prefix)/lib "`

**Comment by nmhamster** [comment]
This issue is fixed provided only 64-bit libraries are used. Reopen if this issue persists.
