### ISSUE TITLE
Trac: #442 SST Problem list with GCC-5.1

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#19]
The compiler segment faults attempting to build Patterns -- Issue 439. 

There is an sst seg-fault in the qsim test. 

The Prospero PIN library appears to be incompatible with gcc-5.1. 

The SST build gets an ugly number of warning from Boost (1.56). 

With a dot-ignore in pattern, successfully ran 27 test Suites with 98 tests in addition to the 150 tests in the Ember Sweep test.

**Comment by allevin** [comment]
Revision #10284 avoids the segment fault; issue #439 has been closed. Other problems unchanged.
comment:2

**Comment by allevin** [comment]
Suppressing the Ariel build on the GCC-5.x test runs. The C++ ABI is incompatible between the pin-2.14-71313-gcc.4.4.7-linux library and GCC-5.x

**Comment by bjmoor** [comment]
As "patterns" no longer exists, are we at the point that this issue can close?

**Comment by bjmoor** [comment]
With nobody chiming in to say this issue should remain open, I'm closing it.
