### ISSUE TITLE
--output-config pyfile.py option yield invalid Python in two cases

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-core#193]
On CramSim the --output-config option yield Python with a broken line.  Here is a sample file begining:
```
# Automatically generated by SST
import sst

# Define SST Program Options:
sst.setProgramOption("timebase", "1ns
")
sst.setProgramOption("stopAtCycle", "110000ns
")

# Define the SST Components:
comp_AddrHash0 = sst.Component("AddrHash0", "CramSim.c_AddressHasher")
comp_AddrHash0.addParams({
     "bankPolicy" : "0\n",
     "boolAllocateCmdResACT" : "0\n",
     "boolAllocateCmdResPRE" : "0\n",
     "boolAllocateCmdResREAD" : "1\n",
```
-------------------------------------------------------------
The "set.setProgramO..." lines are broken.   (If they are manually merged the file is acceptable to be read by SST.

-------------------------------------------------------------------------------------------

On the simpleLookupTableComponent, when it attempt to read the generated Python (which is fairly long), it chokes thusly:
```
 File "/home/jpvandy/CentOS-runJnk-Mar14_0941/devel/sqe/test/testInputFiles/test_simpleLookupTableComponent.py", line 9
    comp_Table Comp 0 = sst.Component("Table Comp 0", "simpleElementExample.simpleLookupTableComponent")
                  ^
SyntaxError: invalid syntax
FATAL: SSTPythonModel Execution of model construction function failed.
-------------------------------------

-----------------------------------------------------
Issue #26, about invalid python on embernightly, has been closed after being fixed.

**Comment by jpvandy** [comment]
@bjmoor Appears to me that simpleLookup is fixed, but I'm seeing the same broken line in CramSim

**Comment by bjmoor** [comment]
At this point, I believe it is actually a bug in CramSim.    It reads configuration variables out of a text file, and includes the newline in the token for the values.

Compare what happens if you change line 86 of test_txntrace4.py from:
```python
           l_tokens = l_line.split(' ')
```
to
```python
           l_tokens = l_line.split()
```

By removing the explicit "Split on space", and going to the implicit "Split on whitespace", the newlines should disappear.
