### ISSUE TITLE
The Python from the --output-config option yields different output than the original in 5 cases.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-core#194]
For Ariel, the sandy bridge test and the ivy bridge test yield outputs that are 10,000 lines longer.
For Merlin, the trafficGen test yields an output file 110 lines longer.
for simpleStatistics, there are 69 extra lines of output.
For VaultSim, the sdl1 test has 4 extra lines of output.
Embernighty has only the completion line without 6 additional that were in the original.

**Comment by jpvandy** [comment]
@bjmoor    Merlin, simpleStatistic, and VaultSim look good.
Ariel: the excess output is down to 216 and 147 lines.
Embernightly seems to be missing 7 lines.  (I would guess the 6 listed above was not quite right.)

**Comment by bjmoor** [comment]
For Ariel, the python config for IvyBridge sets an environment variable `$OMP_NUM_THREADS`.  When I manually set that to the same value which the IvyBridge tests sets it, I get (when sorted, and ignoring sim time) identical output.  The Ariel IvyBridge file also prints to the screen a handful of lines.  These cannot be reconstructed from SST.   All of the above stand the same for my testing with the ariel_snb.py test.

It is quite possible that the "missing" lines from EmberNightly are also print statements in the Python.

**Comment by bjmoor** [comment]
@jpvandy Is this still an issue?

**Comment by jpvandy** [comment]
No.   This is not still an issue.
The SQE tests were looking for exact match of output.
There were print statements in those input files that are not carried to the generated file.

As Branden noted, that's to be expect, but not an "error" in the sst output.
