### ISSUE TITLE
Trac: #450 zoltan partitioner and --disable-mpi

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#20]
When the user runs .configure --disable-mpi --with-zoltan=somepath, Configure will report an error that Zoltan was not found. This is not accurate, rather, the Zoltan autoconf checks require the MPI compilers (#include <mpi.h>), which are not being used. 

Two items: 
1) We should give a better error in this case 
2) With future multi-thread support, Zoltan partitioning may still be desired in a non-MPI build.

**Comment by jjwilke** [comment]
@feldergast 
@nmhamster 
I don't see anything in the `git log -p` that would suggest it got fixed. 
I would recommend `SST_CHECK_MPI` set a flag - and if the flag is not set `SST_CHECK_ZOLTAN` crashes with a sensible error message.  

I don't see that we can do much about using zoltan without an MPI compiler. I suspect removing `mpi.h` from `zoltan.h` will be a headache.
