### ISSUE TITLE
Race condition for two threads AND two ranks on CentOS 7 sst-test?

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-core#212]
On sst-test, 2x2 runs cleanly most of the time.   The full 2x2 Project has been running on sst-test every two hours since March 30th.    The only failures have been a variable number of time limits in one of the 12 runs each morning.   Almost all have been in the run that begins at about 4:20 AM.  (the exception was in the run that started at 2:20 on March 2nd.)

Feels like a load dependant race condition?

@bjmoor @nmhamster @feldergast 
Here is a trace back from memH sdl8-1 this morning in the 4:20 run.
(there are 8 others available on Jenkins.)

'''
         Invoke the traceback routine
$SST_ROOT/test/utilities/stackback.py --mpi 14501

Tracing PIDs ['14505', '14506']
 ('clone()', '/lib64/libc.so.6')
     ('start_thread()', '/lib64/libpthread.so.0')
         ('??()', '/lib64/libstdc++.so.6')
             ('start_simulation()', 'main.cc:327')
                 ('SST::Simulation::run()', 'simulation.cc:542')
                     ('SST::SyncManager::execute()', 'syncManager.cc:178')
                         ('SST::RankSyncParallelSkip::execute()', 'rankSyncParallelSkip.cc:157')
                             ('SST::RankSyncParallelSkip::exchange_slave()', 'rankSyncParallelSkip.cc:191')
                                 ('try_remove()', '../../../src/sst/core/threadsafe.h:286')
                                     ('lock_guard()', '/usr/include/c++/4.8.2/mutex:414')
                                         ('lock()', '../../../src/sst/core/threadsafe.h:127')
                                             ('compare_exchange_weak()', '/usr/include/c++/4.8.2/bits/atomic_base.h:534')
                                                 ['14505.2', '14506.2']
         ('orte_progress_thread_engine()', '/usr/local/module-pkgs/mpi/OpenMPI/openmpi-1.8.8/lib/libopen-rte.so.7')
             ('opal_libevent2021_event_base_loop()', 'event.c:1633')
                 ('poll_dispatch()', 'poll.c:165')
                     ('poll()', '/lib64/libc.so.6')
                         ['14505.3', '14506.3']
 ('main()', 'main.cc:712')
     ('start_simulation()', 'main.cc:327')
         ('SST::Simulation::run()', 'simulation.cc:542')
             ('SST::SyncManager::execute()', 'syncManager.cc:178')
                 ('SST::RankSyncParallelSkip::execute()', 'rankSyncParallelSkip.cc:152')
                     ('SST::RankSyncParallelSkip::exchange_master()', 'rankSyncParallelSkip.cc:294')
                         ('PMPI_Test()', '/usr/local/module-pkgs/mpi/OpenMPI/openmpi-1.8.8/lib/libmpi.so.1')
                             ('ompi_request_default_test()', '/usr/local/module-pkgs/mpi/OpenMPI/openmpi-1.8.8/lib/libmpi.so.1')
                                 ['14505.1']
                     ('SST::RankSyncParallelSkip::exchange_master()', 'rankSyncParallelSkip.cc:240')
                         ('SST::Core::ThreadSafe::Barrier::wait()', '../../../src/sst/core/threadsafe.h:98')
                             ('nanosleep()', '/lib64/libpthread.so.0')
                                 ['14506.1']

   Return to timeLimitEnforcer
'''

**Comment by bjmoor** [comment]
This does NOT feel like a race-condition / deadlock issue to me - at least immediately.   Is progress being made, or has it completely halted?   (ie, the send SIGUSR1, wait SIGUSR1 test)?

**Comment by nmhamster** [comment]
There is some relief from this issue when using `map-by numa:PE=2` for OpenMPI (effectively spacing MPI ranks further apart and allowing affinity for threads). This is still under investigation. @jwilso @allevin @jpvandy we may need to update the documentation to account for this in our MPI run lines.

**Comment by bjmoor** [comment]
Any update on this?  Are we yet seeing evidence of a deadlock situation?

**Comment by nmhamster** [comment]
We believe this is now fixed in our configuration management for testing.
