### ISSUE TITLE
Core RNG library needs a binomial distibution

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#217]
The Core RNG library is missing a binomial distribution.

Alternatively, c++11 not has a good set of random number generators and distributions.  Could we make these work instead of providing our own?

**Comment by nmhamster** [comment]
@feldergast for distributions we don't have I would start to use the C++11 for now. For ones we do have, we should these until we can work out what the cross-platform reproducibility etc issues are.

**Comment by calewis** [comment]
@feldergast and @nmhamster do we want to switch to using C++ random?  We would have to be willing to accept certain instabilities to do that.  Are you willing to accept that different standard libraries may return different results for the same inputs?  I believe that the distributions are implementation defined, meaning you have no promise of portability.

**Comment by nmhamster** [comment]
@calewis - we need reproducible random across different compilers, platforms, libraries etc. So we roll our own random for this purpose (see RNG in the core).

**Comment by feldergast** [comment]
Agreed that we need to keep our own in the core.  I requested the binomial distribution so I could switch over a component that used it.  That component is no longer in use.  Closing.
