### ISSUE TITLE
HDF5 autoconf check should verify ABI compatibility

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#220]
Currently, the HDF5 autoconf check verifies that the HDF5 C library works.  It does not currently check for any C++ methods that are sensitive the the GCC C++11 ABI changes.   On systems where HDF5 was built with an older compiler (gcc 4.x) than is being used with SST (ie, gcc 5.x), there is an incompatibility with the ABI.  This should be detected, and HDF5 compilation ruled out.

**Comment by allevin** [comment]
Branden,

Just FYI...

On our CentOS7 machine when running gcc 5.4 I had to add the "-D_GLIBCXX_USE_CXX11_ABI=0" to both the sst-core and sst-elements to properly build

I don't think this is an issue with our Ubuntu machine because has all libraries built with gcc 5.4.

**Comment by bjmoor** [comment]
@allevin   That makes total sense.   When you're using a compiler that defaults to a newer ABI than system libraries were compiled with, you'll need to make everything use the older ABI.   Newer systems that are entirely built with the new ABI will not have any conflicts.

**Comment by nmhamster** [comment]
@bjmoor @allevin - is this good to close now we have the check added?
