### ISSUE TITLE
Order of -I include lines should have sst-core entries first

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#226]
If you have one of the (optional) dependencies (such as Zoltan) installed into the same location as SST is to be installed, and you have an old install of SST in that location already, the compilation of SST will find the old header files first.

```
mpicxx -DHAVE_CONFIG_H -I.  -DTIXML_USE_STL -DSST_BUILDING_CORE=1 -I/usr/local/module-pkgs/boost/boost-1.56.0-nompi_gcc-4.8.5/include -I/home/bjmoor/SST/sst-inst/include -I/usr/include/python2.7 -I/usr/include/python2.7
 -I../../.. -I../../.. -I../../../src -I../../../src   -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -Wall -Wextra -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.cc
```

As you can see, the `-I/home/bjmoor/SST/sst-inst/include` is found before the `-I../../../` (and such).  Thus, the pre-installed versions of the headers will be found before the "local" ones.

We should look into trying to re-organize the order of the `-I` flags to allow the "local" SST includes to be found before installed SST includes.

**Comment by nmhamster** [comment]
@bjmoor - closing issue. Please re-open if this re-occurs.
