### ISSUE TITLE
can not build sst/core

### ISSUE THREAD

**Issue by YongjunZHENG** [sstsimulator/sst-core#239]
**I use INTELMPI (the same error using OpenMPI with gcc), here are the detail information:**
**$ uname -a**
Linux beaufixlogin2 2.6.32-642.15.1.el6.x86_64 #1 SMP Mon Feb 20 02:26:38 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
**$ gcc --version**
gcc (GCC) 5.3.0
**$ icc --version**
icc (ICC) 17.0.1 20161005

**$ autogen.sh**
**$ ./configure --with-boost=/home/gmap/mrpm/zhengy/softs/boost --prefix=/home/gmap/mrpm/zhengy/softs/sst/sst-core CC=mpiicc CXX=mpiicpc MPICC=mpiicc MPICXX=mpiicpc**
-------------------------------------------------------
SST Core Configuration completed.
-------------------------------------------------------
Build Environment:

                      SST-Core Version : -dev
                            Git Branch : master
                          Git HEAD SHA : 948df1672698752e061a371f239a859d26fcb651
                   Branch Commit Count : 8158
                                Prefix : /home/gmap/mrpm/zhengy/softs/sst/sst-core
                          Preprocessor : mpiicc -E
                          C++ Compiler : mpiicpc
                            C Compiler : mpiicc
                      Compiler Version : icc (ICC) 17.0.1 20161005
                        MPI C Compiler : mpiicc
                      MPI C++ Compiler : mpiicpc
                  MPI Compiler Version : icc (ICC) 17.0.1 20161005
                                Linker : /opt/softs/libraries/GCC5.3.0/binutils-2.26/bin/ld -m elf_x86_64
                  Preprocessor Options : -I$(top_builddir) -I$(top_srcdir) -I$(top_srcdir)/src -I$(top_builddir)/src 
                    C Compiler Options : -g -O2 -Wall -Wextra
                  C++ Compiler Options : -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -Wall -Wextra
               C++ Standard Compliance : C++1Y/14
                        Linker Options : 
-------------------------------------------------------
Configuration Information (Dependencies):

                         Boost Library : YES
            Boost Library Preprocessor : -I/home/gmap/mrpm/zhengy/softs/boost/include
          Boost Library Linker Options : -L/home/gmap/mrpm/zhengy/softs/boost/lib
                    Zoltan Partitioner : No
                          HDF5 Support : No
              libz compression library : YES
-------------------------------------------------------

**The autogen.sh and configure work fine, but the make produced a lot of undefined reference error as following:**
**$ make -j 20**
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1083: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1083: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1083: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1083: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)':
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/opt/softs/gcc/5.3.0/include/c++/5.3.0/bits/basic_string.h:1167: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `TiXmlAttribute::~TiXmlAttribute()':
/home/gmap/mrpm/zhengy/sst/sst-core/src/sst/core/tinyxml/tinyxml.h:781: undefined reference to `operator delete(void*, unsigned long)'
tinyxml/tinyxmlparser.o: In function `TiXmlDocument::~TiXmlDocument()':
/home/gmap/mrpm/zhengy/sst/sst-core/src/sst/core/tinyxml/tinyxml.h:1411: undefined reference to `operator delete(void*, unsigned long)'
make[5]: *** [sstsim.x] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [sstinfo.x] Error 1
make[5]: Leaving directory `/home/gmap/mrpm/zhengy/sst/sst-core/src/sst/core'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/gmap/mrpm/zhengy/sst/sst-core/src/sst/core'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/gmap/mrpm/zhengy/sst/sst-core/src/sst/core'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/gmap/mrpm/zhengy/sst/sst-core/src/sst'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/gmap/mrpm/zhengy/sst/sst-core/src'
make: *** [all-recursive] Error 1

Could you please show me how to solve this build error? Thank you in advance!

Yongjun ZHENG

**Comment by nmhamster** [comment]
@YongjunZHENG - I ran a local build on one of our clusters using Intel 17.0.1 compiler with GCC 5.2.0 (we don't have 5.3.0 on that specific machine), with OpenMPI 1.10 and the build completed successfully. Is the Intel compiler you are using able to compile any C++ which uses strings successfully? Did you also ensure you had the GCC loaded for `configure` and `make`? It might be worth just running a `make clean` and `make` again to check. Please let us know how you get on as we would like to understand the compiles on Intel if there are bugs. Thanks for reporting this issue.

**Comment by bjmoor** [comment]
Missing symbols to std::string with GCC 5.x and above, typically means that you are combining​ libraries at different​ C++ ABI levels.   In general, it is recommended to avoid mixing programs and libraries compiled with GCC 4 and GCC 5.  You can add a CXXFLAG to tell GCC 5 to revert to the older ABI form, which will probably fix your problem.

________________________________________

**Comment by nmhamster** [comment]
@YongjunZHENG - has advice @bjmoor or info in this issue helped you to compile successfully?

**Comment by YongjunZHENG** [comment]
Thank you so much!
After degrade gcc to 4.81, now I can build sst/core.

Yongjun ZHENG







At 2017-05-03 05:59:59, "Branden Moore" <notifications@github.com> wrote:
Missing symbols to std::string with GCC 5.x and above, typically means that you are combining libraries at different C++ ABI levels. In general, it is recommended to avoid mixing programs and libraries compiled with GCC 4 and GCC 5. You can add a CXXFLAG to tell GCC 5 to revert to the older ABI form, which will probably fix your problem.

________________________________________

**Comment by nmhamster** [comment]
@YongjunZHENG thanks for your help and for reporting your issues to the SST team. Please let us know if there is anything else we can help you with.
