### ISSUE TITLE
Trac: #467 configure of boost threads fails on sst-devel

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#24]
checking for boost/filesystem.hpp... yes
configure: Performing linking checks for Boost Filesystem...
configure: Boost Filesystem configuration successful.
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... no
checking for exit in -lboost_thread... (cached) no
checking for exit in -lboost_thread... (cached) no
configure: error: Could not link against boost_thread !
make: * [config.status] Error 1
[mjleven@sst-devel build]$

**Comment by bjmoor** [comment]
with the split core, sst-core does not use Boost::threads.   Should this be a bug on scheduler?
