### ISSUE TITLE
Trac: #456 configure doesnt check for zlib.h

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#25]
.configure should check for the existence of zlib.h

**Comment by allevin** [comment]
SST does check already check for the Z-Lib:
```
AC_CHECK_HEADER([zlib.h], [], [sst_check_libz_happy="no"])
```
during configure. 

Can you describe the error you are seeing in this?

**Comment by allevin** [comment]
I was building on a clean CentOS 7 VM image, and did not have zlib-devel installed. configure succeeded, but later, the build failed due to being unable to find zlib.h.

**Comment by nmhamster** [comment]
What element was this bug found in?

**Comment by nmhamster** [comment]
@bjmoor - can you recall what element this happened in? I think it's because elements don't actually use the correct automake variables and rely on SST magic,

**Comment by bjmoor** [comment]
I do not.    As the build-system has been revamped, I'll assume this fixed for now.   To be re-opened if anybody sees this issue again.

**Comment by bjmoor** [comment]
On a fresh CentOS 7 VM, without zlib-devel installed, `./configure` passes, but we fail to compile `statapi/statoutputcsvgz.cc` due to a missing `zlib.h` file.

**Comment by bjmoor** [comment]
It appears that we *DO* check for zlib.h, but we do not fail the `./configure` if it is not found.  @nmhamster - You're our autoconf "expert."
