### ISSUE TITLE
Trac: #459 --output-config pyFile option creates invalid Python on embernightly

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#26]
emberLoad.py is used as input to a number of tests. The "--output-config" option seems to be yielding invalid Python on these.

Here is a sample snip-it:

```
# Automatically generated by SST
import sst
# Define SST Program Options:
sst.setProgramOption("timebase", "1 ps")
sst.setProgramOption("stopAtCycle", "0 ns")
# Define SST Statistics Options:
# Define the SST Components:
comp_rtr_0x0x0 = sst.Component( < < < < < < < Broken line
rtr.0x0x0", "merlin.hr_router")
comp_nic0 = sst.Component(
nic0", "firefly.nic")
comp_nic0.addParams({
"link_bw" : """4GB/s""",
"nic2host_lat" : """150ns""",
"num_vNics" : """1""",
"packetSize" : """2048B""",
"module" : """merlin.linkcontrol""",
"rxMatchDelay_ns" : """100""",
"verboseLevel" : """0""",
"buffer_size" : """14KB""",
"txDelay_ns" : """50""",
"nid" : """0"""
})
```

**Comment by bjmoor** [comment]
@nmhamster Does this bug still exist?  If so, can you provide a full example?

**Comment by jpvandy** [comment]
The invalid python for Embernightly as been fixed.
Issue 194 reports that the embernightly test still does NOT reproduce results using the python.

Issue #193 points out two other cases that still generate invalid python.  (CramSim and simpleLookupTableComponent.)
