### ISSUE TITLE
Python paths issue

### ISSUE THREAD

**Issue by Christian9212** [sstsimulator/sst-core#261]
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement
I am encountering an issue regarding the installation of SST 7 (http://sst-simulator.org/SSTPages/SSTMainDownloads/). Everything works as it should untill i use the configure script that fails at checking python paths.

checking for python-config... NOTFOUND
checking Python.h usability... no
checking Python.h presence... no
checking for Python.h... no
checking python libraries... 
configure: error: Python was not successfully located but this is a prerequisite to build SST

Did anyone else encounter this issue?

2 - Describe how to reproduce
Runing the configure like this:
./configure --prefix=/home/ubuntu-sim/SST/local/sst_core-7 --with-boost=/home/ubuntu-sim/SST/local/packages/boost-1_64

3 - What Operating system(s) and versions 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

4 - What version of external libraries (Boost, MPI)
Boost 1.64
mpiexec (OpenRTE) 1.10.2
gcc version 5.4.0 20160609
which python --> /usr/bin/python

=======

**Comment by nmhamster** [comment]
@Christian9212 thanks for reporting this issue. Do you have the `config.log` file available from your configure? If so can you post it or email it in to us so we can see why the Python was not detected? My initial guess is that you have Python installed but not the `python-devel` packages which are usually required. Can you verify that the development headers etc are available?

**Comment by Christian9212** [comment]
Hi nmhamster,

Thx for the reply, sure, i have attached the config.log. Can you plese be a bit more specific about the development headers?

Thx!
[config-log.txt](https://github.com/sstsimulator/sst-core/files/1040612/config-log.txt)

**Comment by Christian9212** [comment]
Confirming that after installing the python devel, it worked, but, after make, this happened:

CXXLD    sstinfo.x
/usr/bin/ld: elemLoader.o: undefined reference to symbol 'dlsym@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1194: recipe for target 'sstinfo.x' failed
make[5]: *** [sstinfo.x] Error 1
make[5]: Leaving directory '/home/ubuntu-sim/Co/SST-Simulator/sstcore-7.0.0/src/sst/core'
Makefile:1447: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/ubuntu-sim/Co/SST-Simulator/sstcore-7.0.0/src/sst/core'
Makefile:882: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/ubuntu-sim/Co/SST-Simulator/sstcore-7.0.0/src/sst/core'
Makefile:480: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst'
Makefile:422: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu-sim/Co/SST-Simulator/sstcore-7.0.0/src'
Makefile:520: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Christian9212** [comment]
If i use export LDFLAGS="-ldl", it no longer crashes, but .... python does

model/pymodel.o: In function `setSSTThreadCount':
/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst/core/model/pymodel.cc:314: undefined reference to `PyLong_AsLong'
model/pymodel.o: In function `getSSTMPIWorldSize':
/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst/core/model/pymodel.cc:303: undefined reference to `PyInt_FromLong'
model/pymodel.o: In function `getProgramOptions':
/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst/core/model/pymodel.cc:245: undefined reference to `PyDict_New'
/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst/core/model/pymodel.cc:246: undefined reference to `PyString_FromString'
/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst/core/model/pymodel.cc:246: undefined reference to `PyString_FromString'
/home/ubuntu-sim/CoFLuent/SST-Simulator/sstcore-7.0.0/src/sst/core/model/pymodel.cc:246: undefined reference to `PyDict_SetItem'

If i use LDFLAGS=' ', python works, but crashes as mentioned in the comment above.

**Comment by nmhamster** [comment]
@Christian9212 - thanks for sending in the additional information. I am sorry you are having so much trouble here. SST checks for a tool called `python-config` in your environment which is able to provide all the configuration settings (e.g. header files, libraries etc) that we should use to compile Python into the code. The configure that you sent looks like it does not find Python installed for development. Can you try running the following and posting this as a reply (this will ensure that Python is installed for development). The output below is shown for my Mac OS-X Sierra workstation, so yours will be different but its important we check there are values for each one since SST requires these.

I think somewhere you had said you were using Ubuntu. If you are, can you check `apt-get install python-devel` as well, just to ensure the package is installed.

Thanks again!

```
$ python-config --includes
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
```

```
$ python-config --libs
-lpython2.7 -ldl -framework CoreFoundation
```

```$ python-config --ldflags
-L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation
```

**Comment by Christian9212** [comment]
@nmhamster - Thx a lot for the info, sorry for the late response. I had to reinstall the OS, and tried again from step 0, and.... It worked, don't know what happened..

Regarding the python-config, here they are from the machine before installing the OS:

python-config --includes
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7

python-config --libs
-lpython2.7 -lpthread -ldl  -lutil -lm 

python-config --ldflags
-L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions

Thx a lot for the info!

**Comment by nmhamster** [comment]
@Christian9212 - thanks for the info. I am happy you have a working SST! Please let us know if you have any other questions relating to SST that we can help with. For now, I'll close this issue. Please re-open if we need to get back to you on it.
