### ISSUE TITLE
Is the SST core supposed to require mpi to build?

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-core#269]
The Nightly test, Nightly_memH_without openMP, loads openmp-1.8 and the core fails to configure without it.

That appears to be the only current Jenkins project which considers the issue.

I find evidence in December of 2016 for building the core without mpi

(There is a bamboo.sh Scenario, sstmainline_config_no_mpi.)

**Comment by nmhamster** [comment]
@jpvandy - no. MPI is not *required* to build.

**Comment by bjmoor** [comment]
MPI is not required to build, but it currently is required, unless `--disable-mpi` is passed to `configure`.   The decision to make it required to explicitly disable was made long ago, and I'm open to changing that.  @nmhamster , thoughts?

**Comment by jpvandy** [comment]
This is totally a misinterpretation of various things on my part.
@nmhamster @bjmoor @feldergast
