### ISSUE TITLE
Trac: #313 support for stopAtWalltime

### ISSUE THREAD

**Issue by allevin** [sstsimulator/sst-core#27]
Currently sst provides setProgramOption stopAtCycle option to stop simulation at certain simulation time. As majority of actual sst simulation jobs are submitted to be run on machine which have queue limits. It would be beneficial if there is option like stopAtWalltime so that simulation could be exited by the allocated time and users can get some result back rather than program termination.

**Comment by bjmoor** [comment]
Completed in PR #179
