### ISSUE TITLE
sst-config broken when installed to default `$prefix`

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#270]
If a user does a clean install of SST with no `--prefix` on the `./configure` line, SST installs into `/usr/local/` as expected.   However, `sst-config` complains that:
```SST: Unableto open configuration file 'NONE/etc/sst/sstsimulator.conf'```

Also, when then attempting to build `sst-elements`, `./configure` succeeds, but at build time, errors are thrown due to an inability to find `sst_config.h`.  The include paths are:
```-I. -I../../../../src -I/include/sst/core -I/include```

Seen on a LOFT install of OSX 10.11.6.

**Comment by nmhamster** [comment]
@bjmoor working on this now. You can use the environment variable to fix this in the field for now.

**Comment by bjmoor** [comment]
Fixed in #272
