### ISSUE TITLE
Statistics API bug:  Values shown in histogram bin labels can overflow.

### ISSUE THREAD

**Issue by mikepfrank** [sstsimulator/sst-core#28]
In file sst/core/statapi/stathistogram.h, template class HistogramStatistic<BinDataType>, private member function registerOutputFields():

When the bin fields are generated in the for loop, the generated field name includes the range of bin values, formatted as <binLL>-<binUL>, where the lower and upper limits are formatted in decimal.

Sometimes, as in the case of collecting histograms over memory address ranges, BinDataType ends up being instantiated as a 64-bit type (uint64_t).  Meanwhile, the number of bins (returned by getNumBins()) is always assumed by the code to fit in 32 bits (due to the uint32_t type on the bin index y), and meanwhile getBinWidth() (whose type is HistoBinType) may also return a value declared as 32 bits.

Therefore, in the following line of code which calculates binLL:

                binLL = (y * getBinWidth()) + getBinsMinValue(); 

the multiplication operator here can be doing a 32-bit multiply (since both operands are 32 bits), yet the result may not actually fit in 32 bits, in which case the result of the multiplication expression will overflow and be truncated to 32 bits before being stored in binLL, and so, a corrupt value may end up in binLL (and also binUL).  This will result in the bin field labels being incorrect, which may lead to incorrect display or sorting of data in some later processing of the output .csv file.

This can happen, in particular, when running memsieve to collect memory access histograms over address ranges which exceed the 4GB limit for 32-bit addresses.  The bin width (page size) and number of bins can both be declared as 32-bit values, yet their product may not fit in 32 bits.  E.g., in the example sst configuration for sieve, I encountered the particular case where 4 million bins representing memory pages of size 4 KB each were being generated, so that the address ranges spanned a full 16GB.

However, the overflow is easily avoided by forcing the above expression to always invoke a 64-bit multiply operation, by casting either of the multiplicands to 64 bits before the multiplication occurs, e.g.:

                binLL = (y * (uint64_t)getBinWidth()) + getBinsMinValue(); 

And in cases when BinDataType happens to be only 32 bits, this change is harmless.

The above change has been implemented in a branch labeled "bugFix_binLabelOverflw" which I will push to the sst-core repository.

**Comment by allevin** [comment]
This issue is is corrected.  Issue is closed.
