### ISSUE TITLE
Time types could map to std::chrono types

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#280]
This issue is to discuss potentially mapping SST's time object (TimeConverters, etc) to C++11's std::chrono types.

This would have a potential benefit of being more standard's inter-operable:

* `SimTime_t` could become a `std::chrono::time_point`
* We could define a `SimulationClock` which maps to the C++ concept of a Clock
* `TimeConverter` might be able to map to things like `std::chrono::nanoseconds`
* We could use the `std::literals::chrono_literals`

**Comment by jjwilke** [comment]
Do we still want this? It could be a nice feature. We have considered implementing something very similar for SST/macro skeletons. 

I would suggest just adding some `getChronoTime` functions that return the internal `uint64_t` as a c++ chrono object.

**Comment by feldergast** [comment]
Will not be providing this support.
