### ISSUE TITLE
Ability to repeatedly add same value to a statistic in a single call

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-core#283]
It would be good to support adding the same value to a statistic N times in a single call. 

This comes up for components that are counting some value on every clock cycle (say occupancy of a buffer) and are being de-clocked when they are idle. When the clock is re-enabled, to ensure the statistic count/sum-of-squares are correct, I end up doing:
for (i = 0; i < num_cycles_unclocked; i++) { stat->addData(buffer_size); }

But it would be more convenient and probably faster to only update the statistic once using a call like stat->addRepeatedData(num_cycles_unclocked, buffer_size)

**Comment by jjwilke** [comment]
@gvoskuilen 
Do we still want this feature? The new multi-statistics make this pretty straightforward. I can add it milestone 9.0, if so.

**Comment by jjwilke** [comment]
Related to #381

**Comment by gvoskuilen** [comment]
@jjwilke Yes I still want this.

**Comment by jjwilke** [comment]
Okay. I will push this to 9.0 milestone and try to finish it next week.
