### ISSUE TITLE
Link::recv() does not check to make sure Link was set as polling link

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#290]
If a user calls Link::recv() for a link with an EventHandler installed, it should call Output::fatal.  When recv() is called on a non-polling link, the call simply pulls the first item off the TimeVortex and returns it to the user.

**Comment by bjmoor** [comment]
@feldergast  This is fixed in #300 , correct?

**Comment by feldergast** [comment]
Fixed in #300
