### ISSUE TITLE
mempool corruptions occurs on POWER8

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#298]
With various threaded simulations on POWER8, SST crashes with very weird bugs.  Looks like events are getting modified.

Building the core with `--disable-mem-pools` appears to fix the issue.

* -n 60 sdl9-2.py
* -n 2 sdl8-1.py

**Comment by nmhamster** [comment]
Same errors are seen on POWER7+ development systems.

**Comment by nmhamster** [comment]
Disabling memory pools on POWER7+ allows memHierarchy tests to pass.

**Comment by bjmoor** [comment]
Duplicate of #297 
Spinlock doesn't work on POWER8

**Comment by nmhamster** [comment]
Addressed in #299. Reopen is problem reoccurs.
