### ISSUE TITLE
Marsaglia does not use enough random data for 64bit results

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#30]
Marsaglia's RNG system only uses 32bits of random data to calculate a 64bit value (double, Int64, UInt64).  This leads to cases where the results appear non-random.  (For example, most of the time, a call to `generateNextUInt64()` will return a number that is a multiple of 512.)

**Comment by nmhamster** [comment]
Do you have a test case which shows this up?

**Comment by bjmoor** [comment]
I looked at the addresses coming out of the Miranda GUPS generator.  If you look at the RNG implementation, it takes a 32bit int, and multiplies it with two constants to get a 64bit number.  Obviously, that isn't adding additional random information - it just scales the number to cover a larger space.

________________________________________

**Comment by nmhamster** [comment]
Think this is address in pull request #40 (now merged).
