### ISSUE TITLE
Release tarball contains sst_config.h in src/ directory that causes out-of-source builds to fail

### ISSUE THREAD

**Issue by KarateSnowMachine** [sstsimulator/sst-core#302]
I downloaded the latest sst tarball (7.1.0) and the default distribution contains the file ./src/sst/core/sst_config.h . When I tried to do an out-of-source build, this default file was picked up instead of the generated sst_config.h and caused the build to fail. I think in general since this file is generated by configure, it should not be distributed as part of the tarball.

**Comment by nmhamster** [comment]
@KarateSnowMachine - can you try SST 7.2.0 release?

**Comment by allevin** [comment]
Fixed by PR #333
