### ISSUE TITLE
No barrier between component finish() and statistic engine shutdown

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-core#312]
In multithreaded execution, the call to the statistic engine to dump end of simulation statistics doesn't wait for all threads to shutdown their components first. This means statistic updates during a component's finish() are not always caught by the final statistic output.

**Comment by feldergast** [comment]
This should have been fixed in PR #311.  We can close this once it's been successfully tested.

**Comment by jpvandy** [comment]
Nightly has seen no failures since PR #311

**Comment by feldergast** [comment]
Issue fixed in PR #311.
