### ISSUE TITLE
documentation website http://sst-simulator.org/ is inaccessible

### ISSUE THREAD

**Issue by aapocketz** [sstsimulator/sst-core#370]
1 - Detailed description of problem or enhancement

The website http://sst-simulator.org/ appears to be down, I get a godaddy domain name expired notice

2 - Describe how to reproduce

visit http://sst-simulator.org/

Thanks!

**Comment by jwilso** [comment]
The domain renewal has been submitted. The sst-simulator.org domain should be working properly again shortly.

**Comment by jwilso** [comment]
@nmhamster sst-simulator.org domain is now redirecting properly to our site. Closing this issue.

**Comment by nmhamster** [comment]
@jwilso - thanks for your help. :)
