### ISSUE TITLE
SharedRegionMerger::merge() with change sets does not detect conflicts

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#38]
The merge() function in SharedRegionMerger copies the change set data without checking for conflicts.  I'm not sure if the conflict check is supposed to happen elsewhere, but I was able to write multiple times to the same location in a shared region, and neither the local SharedRegionManager nor the merge detected the conflicts.

**Comment by bjmoor** [comment]
Fixed in PR #101
