### ISSUE TITLE
Attaching miranda request generator to BaseCPU slot crashes SST on cleanup

### ISSUE THREAD

**Issue by luisfnqoliveira** [sstsimulator/sst-core#387]
Found a problem when configuring a simulation that attaches a miranda request generator, e.g. miranda.STREAMBenchGenerator, to miranda.BaseCPU using the setSubComponent function. 

```python
BaseCPU = sst.Component("BaseCPU", "miranda.BaseCPU")
STREAMBenchGenerator = BaseCPU.setSubComponent("generator", 
                                               "miranda.STREAMBenchGenerator", 0)
```

The simulation runs to completion and generates output. However, it crashes with a double free or corruption error when deleting the simulation (sst-core/src/sst/core/main.cc:353).

```bash
double free or corruption (fasttop)
[archie:29010] *** Process received signal ***
[archie:29010] Signal: Aborted (6)
[archie:29010] Signal code:  (-6)
[archie:29010] [ 0] /usr/lib/libpthread.so.0(+0x123c0)[0x7f276264e3c0]
[archie:29010] [ 1] /usr/lib/libc.so.6(gsignal+0x10f)[0x7f276182fd7f]
[archie:29010] [ 2] /usr/lib/libc.so.6(abort+0x125)[0x7f276181a672]
[archie:29010] [ 3] /usr/lib/libc.so.6(+0x7a878)[0x7f2761872878]
[archie:29010] [ 4] /usr/lib/libc.so.6(+0x8118a)[0x7f276187918a]
[archie:29010] [ 5] /usr/lib/libc.so.6(+0x82b27)[0x7f276187ab27]
[archie:29010] [ 6] sst(_ZN3SST13ComponentInfoD1Ev+0xdd)[0x55ebecbc904d]
[archie:29010] [ 7] sst(_ZN3SST13ComponentInfoD1Ev+0x117)[0x55ebecbc9087]
[archie:29010] [ 8] sst(_ZN3SST10SimulationD2Ev+0xb9)[0x55ebecc13ea9]
[archie:29010] [ 9] sst(+0x8cfb7)[0x55ebecbb5fb7]
[archie:29010] [10] sst(main+0xf96)[0x55ebecba8486]
[archie:29010] [11] /usr/lib/libc.so.6(__libc_start_main+0xf3)[0x7f276181c223]
[archie:29010] [12] sst(_start+0x2e)[0x55ebecbb58fe]
[archie:29010] *** End of error message ***
[1]    29010 abort (core dumped)  sst simulation.py
```

This does not happen if parameter "generator" is set instead.
```python
BaseCPU = sst.Component("BaseCPU", "miranda.BaseCPU")
BaseCPU.addParams({
    "generator": "miranda.STREAMBenchGenerator"
})
```

Not sure this is a core or elements bug, as `sst-elements/src/sst/elements/simpleElementExample/tests/test_simpleSubComponent.py` runs without error.

To reproduce, run the simulation file attached.
[simulation.txt](https://github.com/sstsimulator/sst-core/files/2966467/simulation.txt)

Problem detected on Archlinux using:
  - SST core master (commit sstsimulator/sst-core@3d5607f75f8912107246af8c38bc70c85e67915e)
  - SST elements master (commit sstsimulator/sst-elements@4d5643fb8c29c3e0a26c91e6913c12d238d6ee93)
  - OpenMPI  2.1.3
  - Without boost (--without-boost)

Also replicated in Occam using 8.0.0:
    - https://occam.dev/QmQMZZurQk5qX6g6HNpZzuBrFpuLN9HbhLLUPRpNR1rnLT/5ds39gxaGQAkttdphz2kNELNxpBmqC

**Comment by jjwilke** [comment]
Is there a valgrind output from this?

We might also consider adding Clang address sanitizer builds - see #390

**Comment by luisfnqoliveira** [comment]
valgrid doesn't say a thing. It starts running it, and does not mention any errors.
Let me know if you want me to run any specific command.

**Comment by allevin** [comment]
This will be fixed in SST-10 release
