### ISSUE TITLE
Can SST run on server which has many nodes?

### ISSUE THREAD

**Issue by MaohuiLu** [sstsimulator/sst-core#388]
I want to run SST on my lab server which has many nodes for better performance. I don't find anything about this issue on the official website. So is it possible?

**Comment by nmhamster** [comment]
@MaohuiLu - yes. SST is able to use MPI and Threads to run on multiple nodes. To run using MPI, use a command like:

`mpirun -n 4 ./sst myscript.py`

SST is able to detect it is running using MPI and then perform a partitioning of the elements. You may  want to be selective about which partitioner is used depending on what kind of study you are performing (see `-help` on SST). Can you help advise us what kind of study you are doing (eg. processor, memory or network as the partitioner you select may be different from them).

As a reminder, the partitioner decides how to break up a simulation over MPI ranks. We have schemes such as round-robin and linear, which lists all the components and then breaks them into rough N even slices, allocating 1/N to each MPI rank.

Does that cover what you need? Remember - you must build SST with MPI to enable the multiple node mode.

**Comment by MaohuiLu** [comment]
Thank you for reply!
Now I have a new problem. I am using SST-6.0.0 on Ubuntu-14.04 and then I want to use ariel component, but I should install Intel Pin Tool 2.14-71313 firstly.
There is a known problem of using Pin on Linux systems that prevent the use of ptrace attach via the sysctl /proc/sys/kernel/yama/ptrace_scope. In this case Pin is not able to use its default (parent) injection mode. To resolve this, either use the "-injection child" option or set the kernel/yama/ptrace_scope sysctl to 0.
when I use command "../../../pin.sh -t obj-intel64/opcodemix.so -- /bin/ls" to test if Pin install sucessfully, it shows failed. I must use the "-injection child" option. But I can't use this option when I run sst program.

**Comment by MaohuiLu** [comment]
@nmhamster 
Thank you for reply!
Now I have a new problem. I am using SST-6.0.0 on Ubuntu-14.04 and then I want to use ariel component, but I should install Intel Pin Tool 2.14-71313 firstly.
There is a known problem of using Pin on Linux systems that prevent the use of ptrace attach via the sysctl /proc/sys/kernel/yama/ptrace_scope. In this case Pin is not able to use its default (parent) injection mode. To resolve this, either use the "-injection child" option or set the kernel/yama/ptrace_scope sysctl to 0.
when I use command "../../../pin.sh -t obj-intel64/opcodemix.so -- /bin/ls" to test if Pin install sucessfully, it shows failed. I must use the "-injection child" option. But I can't use this option when I run sst program.
