### ISSUE TITLE
Specialized stat outputs for macro

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#398]
Most stats are structured around a specific set of fields. This is not true for several things that are "stats", but don't easily map into a CSV, HDF5, JSON format. This includes

* OTF2 trace output
* VTK visualizations
* FTQ charts
* Call graphs

In this case, the `Statistic` object should really be in charge of its own output. We should modify
````
StatisticOutput* StatisticProcessingEngine::getOutputForStatistic(const StatisticBase *stat) const
````
A stat object should be able to inherit from `StatisticOutput` and act as its own output.

Additionally, I recommend stashing the StatisticOutput object on the stat itself. This would make that function much more efficient for periodic stats dumps.

**Comment by jjwilke** [comment]
I think the way to fix this will be to generalize statistic outputs. The current stat output is a very specific type of "row-column" database-like output that assumes named fields.

I recommend creating a `StatisticOutputFields` class and defining a more generic public interface for `StatisticOutput`.  None of this is actually API breaking since statistic internals were not part of a public API.

**Comment by allevin** [comment]
Fixed
