### ISSUE TITLE
Dynamic statistic registration

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#400]
Currently stats must be registered during wire-up.  The reason for this restriction (presumably) is because of field registration. Before outputting any stats, all the required fields must be registered. The only way to guarantee no registration after output is the wire-up restriction.

In general, though, this is a very strong restriction - and breaks macro.  Macro dynamically creates apps and their statistics. This can be relaxed in two scenarios:

1) The output supports dynamic registration, e.g. a database that allows dynamic column insertion
2) Fields are not periodic or event-based and only dump at the end of the simulation.  This again guarantees that registrations occur before all outputs

Stat outputs should have a virtual
````
bool supportsDynamicRegistration() const
````
that tells the stat engine not crash on dynamic registration.

Additionally, there should be an additional stat mode `STAT_MODE_DUMP_AT_END` that tells the engine the given stat will only dump at the end, not periodically.

**Comment by allevin** [comment]
Fixed in 9.1
