### ISSUE TITLE
Compilation Issue for Enabling Event Tracking

### ISSUE THREAD

**Issue by amroawad2** [sstsimulator/sst-core#407]
In current devel version in SST core, enabling event tracking by --enable-event-tracking causes a compilation error:

../../../../sst-core/src/sst/core/config.cc: In constructor ‘SST::Config::Config(SST::RankInfo)’:
../../../../sst-core/src/sst/core/config.cc:82:5: error: ‘event_dump_file’ was not declared in this scope
     event_dump_file = "";
     ^~~~~~~~~~~~~~~

**Comment by amroawad2** [comment]
To fix it, you just need to add: 

std::string     event_dump_file;

before line 82 in sst-core/src/sst/core/config.cc

**Comment by allevin** [comment]
Fixed by PR #508
