### ISSUE TITLE
--with-boost/BOOST_CPPFLAGS in sst.conf

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#408]
We still have a `--with-boost` flag in the core. However, we pulled all boost flags out of `sst.conf` in commit 0cddecc9065bd546e5e6afae7ae80a250813935f. 

We should probably do one of the following:
* Put the BOOST_CPPFLAGS back in sst.conf so that different element libraries can point to a common boost defined by the core
* Remove the --with-boost flag from configure. Probably preferred since we don't have any more Boost dependent features

This created confusion for UF customers expecting to be able to still use `sst-config --BOOST_CPPFLAGS` This extends to sst-elements which still has logic that call `sst-config --BOOST_CPPFLAGS`

**Comment by feldergast** [comment]
Let's just remove the --with-boost flag from configure.

**Comment by allevin** [comment]
Boost has been terminated!
