### ISSUE TITLE
error: Unable to find requested partitioner 'sst.single'

### ISSUE THREAD

**Issue by cjobr** [sstsimulator/sst-core#428]
I compiled with icc 18.0.5 20180823  and mpiicc 18.0.5 20180823 . And after configuration ,make ,and make install successfully , I try to run simple example . this error appears:
`FATAL:  SST Core: Error: Unable to find requested partitioner 'sst.single', check --help for information on partitioners` I am looking for solution. It is strange ,when I build with gcc and openmpi ,it's ok.
,and when I compiled with gcc and intel mpi ,same problem appears,

**Comment by jjwilke** [comment]
Intel forces a different set of dlopen flags, which does unfriendly things to the global component, partitioner, etc lookup tables.  We are still trying to figure out if this a bug in the dlopen implementation (i.e. not fixable) or if there is a workaround. It has to do with ODR (one-definition rule) for template global variable when external libraries are opened.

**Comment by cjobr** [comment]
OK, I understood. Thanks for replying.

**Comment by jjwilke** [comment]
Related to #383
