### ISSUE TITLE
sst-info XML output tags subcomponents and modules as components

### ISSUE THREAD

**Issue by luisfnqoliveira** [sstsimulator/sst-core#431]
When generating an XML file with sst-info (e.g. `sst-info -xn`), all `BaseType`s where tagged as "Component" instead of the appropriate tag (Module, SubComponent).

I've made a pull request (#430) that solves this issue by calling `BaseType::ELI_baseName()`.

**Comment by allevin** [comment]
@feldergast I believe that this issue can be closed?  Can you double check and close it...

**Comment by gvoskuilen** [comment]
@feldergast @allevin this is fixed in devel currently, not yet into master

**Comment by allevin** [comment]
Fixed for SST-10
