### ISSUE TITLE
sst-elements configure can silently fail and still produce makefiles

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#433]
sst-core checks can fail (in the current case, missing libmpi) resulting in an empty core prefix. Configure still succeeds and generates makefiles. Make then crashes with strange missing header errors because sst-core is not a valid path.

**Comment by hughes-c** [comment]
Shouldn't this be in sst-elements?

And I don't follow. Are you saying that the install directory for sst-core can be empty and sst-elements will still complete configure successfully?

**Comment by jjwilke** [comment]
Oops. Yes, this is an elements issue. configure completes successfully, but has an empty sst-core.
