### ISSUE TITLE
Include paths bug

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#435]
When configuring sst-core, it appears that the top level source directory gets added as an include path for certain targets.  The top level source directory includes the file VERSION.  Newer versions of cstddef include a file <version>.  

OS X is not case sensitive so when building sst-core/VERSION is included into the code, understandably this leads to a compilation failure.  

As far as I can tell there is no reason that the top level source directory should be added as an include path, so the best solution is probably to remove that include from getting added to the includes.

**Comment by allevin** [comment]
@gvoskuilen to investigate

**Comment by gvoskuilen** [comment]
This is fixed by #505
