### ISSUE TITLE
checkpoint-restart 

### ISSUE THREAD

**Issue by cjobr** [sstsimulator/sst-core#436]
Does anyone  know how to checkpoint/restart in SST 9.0.0 ? I have read the web page of SST. I can't find anything helpful. And , I know in the previous version , it had checkpoint/restart feature. However , I can't find it in 9.0.0 , I'm not sure if I miss anything .

**Comment by gvoskuilen** [comment]
@cjobr SST had checkpoint/restart capability a long time ago, but has not had it in recent versions.

**Comment by cjobr** [comment]
THANKS for reply

**Comment by allevin** [comment]
Question answered
