### ISSUE TITLE
stat info loop doesn't break properly when stat is found?

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#453]
The do/while loop
````
  do {
        curr_info = next_info;
        if ( !curr_info->isAnonymous() ) {
            for ( auto & si : *curr_info->getStatEnableList() ) {
              ...
             nameFound = true;
             break;
....
    } while ( curr_info->canInsertStatistics());
````

The loop continues even if name is found. If the loop continues and name is not found in the next info, we get false even though it was located.  Is this behavior correct? Should the termination here be:

````
    } while ( curr_info->canInsertStatistics() && !nameFound);
````

**Comment by feldergast** [comment]
Yes, the main loop should terminate when nameFound is true.

Sent from my iPad

On Nov 4, 2019, at 1:46 PM, Jeremy <notifications@github.com> wrote:

﻿

The do/while loop

  do {
        curr_info = next_info;
        if ( !curr_info->isAnonymous() ) {
            for ( auto & si : *curr_info->getStatEnableList() ) {
              ...
             nameFound = true;
             break;
....
    } while ( curr_info->canInsertStatistics());


The loop continues even if name is found. If the loop continues and name is not found in the next info, we get false even though it was located. Is this behavior correct? Should the termination here be:

    } while ( curr_info->canInsertStatistics() && !nameFound);

**Comment by allevin** [comment]
fixed
