### ISSUE TITLE
Compile for future release configuration flag

### ISSUE THREAD

**Issue by gvoskuilen** [sstsimulator/sst-core#455]
Add a configure flag so that we can optionally compile without deprecated features, backwards compatibility paths, etc. that are slated to be removed in a future release.

**Comment by jjwilke** [comment]
We would like this ASAP for macro stuff. I just went ahead and added this quickly.

**Comment by jjwilke** [comment]
@gvoskuilen Should we mark this done and add a separate issue for adding all the `ifdef` blocks in the actual code?

**Comment by gvoskuilen** [comment]
@jjwilke Thanks! I'll close this and open a new issue.
