### ISSUE TITLE
Add `configureNonnullLink` function with error checking

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#465]
We may want to have a function which is not allowed to return a `nullptr` link. In many cases, we would rather crash and print a sensible error message rather than continue. This will help avoid difficult to understand segfaults when missing links are used.

**Comment by jjwilke** [comment]
Related to https://github.com/sstsimulator/sst-elements/issues/1401

**Comment by gvoskuilen** [comment]
What's the use case for this? Components should check the return value when they call configureLink and handle nullptr with an error if they don't expect it. A function that does error handling is useful for component writers that forget to error check, but if a writer remembers to use an error-checking variant of configurelink, they're not forgetting error checking and could just do their own. Components are able to generate better error messages than the core, so it seems better to have components do it. Is there some other issue this addresses?

**Comment by jjwilke** [comment]
The main reason is just to make it easier (and therefore encourage more checks).

There seemed to be a lack of error checking in sst-elements, e.g. https://github.com/sstsimulator/sst-elements/issues/1396 (I have not done an extensive survey).  In most cases, you would just want an error message that prints component (or subcomponent name) and link name. In that sense, there's no reason for each element to reinvent error checking if a common helper function works.

If there is a deep nesting of subcomponents, you would actually want a function that could print the entire hierarchy of named subcomponents to tell you exactly which link you forgot to create. In that sense, I think the core could actually print a more meaningful error message than the element.

**Comment by jjwilke** [comment]
No use case in particular. More of a sociological question for the team if requiring nullptr checks and custom error messages was just encouraging us to skip error checks.
