### ISSUE TITLE
Oneshot implementation is inconsistent

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#468]
The Oneshot object inserts schedules itself at current_sim_time + delay, but the registerOneShot function uses a cache based just on delay.  So, a registerOneShot call may create a callback at a different time than expected if another component registered a Oneshot with the same delay, but at a different time (in this case, the second callback would get called early).

How we fix this depends on how we want to use Oneshot in the future.  Do we want Components to continue to have access to Oneshots, or do we want them to just be used by the core (for example, by stats)?

**Comment by gvoskuilen** [comment]
I think it should be left accessible only if there's something we can do with one shot that we can't do with self links, and there's a good use case for having that functionality. So far I don't see any reason to keep it accessible.

BTW there is a very old branch called fixOneShotScheduling that I never merged. I think it solved the issue I had been having with one shots awhile ago. Is it addressing the same issue?

**Comment by feldergast** [comment]
That branch does get rid of the current_sim_time + delay in favor of specifying an absolute time in the Oneshot constructor.  So, I think as long as you put in an absolute time into the registerOneshot call (even though the variable is still called delay), it should work.  So, that would be one possible fix, but would change the semantics to absolute instead of relative time.

**Comment by gvoskuilen** [comment]
I agree relative is probably better. I'll delete that branch.

**Comment by feldergast** [comment]
This has been addressed.  OneShot is now core only.

**Comment by nicmcd** [comment]
@feldergast now that OneShot is a core only feature, what is the mechanism to execute a single future callback? My particular application has N components. Each component starts up at a different time. My thought was to use a OneShot to essentially call a start() function in the future. How should this be done? I'm hoping the answer isn't to create a self link :)

**Comment by feldergast** [comment]
This is exactly what self links were created for.  Sorry.
