### ISSUE TITLE
Build system picks up parent shell's INSTALL value, if set

### ISSUE THREAD

**Issue by e10harvey** [sstsimulator/sst-core#470]
Build system feature
----------------------
1 - Detailed description of problem or enhancement
If INSTALL is set in the environment, configure will populate the generated Makefile with INSTALL = $INSTALL instead of probing the environment's PATH for the `install` program.
2 - Describe how to reproduce
```bash
export INSTALL=TEST
./configure
make install
```
3 - What Operating system(s) and versions 
RHEL8
4 - What version of external libraries (Boost, MPI)
N/A
5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
sst-core:521be9729d702a6986b759200ee127a8029aa8a1
sst-elements:7530e6f88c071c2c13b3ff7cf03a4bc16167cac4
I suspect this issue exists in other sst repos as well

Proposed solution: Update the build system to ignore the value of INSTALL in the user's environment.

**Comment by jpkenny** [comment]
I believe this is the intended behavior of autoconf/automake.  If the user sets INSTALL in their environment then they are telling autoconf that they want that install program and please don't search the path.

**Comment by e10harvey** [comment]
My mistake. See https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#index-INSTALL-271.
