### ISSUE TITLE
Rarely encounter code in core known to NOT be thread safe

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-core#51]
The Merlin Dragon-12 test using 2 threads failed with a segmentation fault that is possibly attributable to taking such a path thru the core.  (This is not a reproducible  failure.)
[Dragon12-seq-fault.txt](https://github.com/sstsimulator/sst-core/files/202773/Dragon12-seq-fault.txt)

**Comment by jwilso** [comment]
Branden: Check with Scott, he did some changes. He switched to using shared regions.

**Comment by feldergast** [comment]
This instance was due to using SimpleNetwork:mapping, which was not thread safe.  This functionality has been removed as SharedRegion is now available.
