### ISSUE TITLE
valid values for timebase

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#525]
What values are valid for setting timebase using sst.setProgramOption?
----------------------
1 - `sst.setProgramOption("timebase", "2ns")` fails with
```Attempting to get TimeConverter for a time (1 ns) which has too small of a period to be represented by the timebase (2 ns)```
It looks like any value greater than 1ns fails.  I would like to use something more like 1ms if possible.

2 - How to reproduce:
Run sst on this python script:
```
import sst
sst.setProgramOption("timebase", "2ns")
```

3 - OS: Debian Linux, 9.12

4 - What version of external libraries (Boost, MPI)
boost-1.62, openmpi-2.0.2

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
Released version sstcore-9.1.0
Looks like the code that aborts was commited with sha1 2cc79f93b135ba026f25257bd0f88219e2f82554 in response to another issue.

6 - Fill out Labels, Milestones, and Assignee fields as best possible

<<<<<<< HEAD
=======

>>>>>>> devel

**Comment by feldergast** [comment]
Any value is technically allowed.  However, you can't represent any time less than the timebase.  The core time is kept by a uint64_t and setting the timebase sets what 1 of these units is equal to.  In general, you probably want your timebase to be at least a factor of 100 (preferably ~1000) smaller that your shortest time interval you want to represent. The default is 1ps to represent numbers in the 1GHz (1ns) range.  If you can tell me more about your use case, I may be able to help with ways to do what you want to do.

**Comment by jjwilke** [comment]
@feldergast  beat me to it.  1ns on a 64-bit integer gives you 18bn seconds of simulation clock.

**Comment by feldergast** [comment]
It should also be noted that setting a larger timebase will not affect the time it takes for the simulator to run.  The core does not "tick" at this rate, but rather skips from event to event.  The only reason to set the time if if you need longer than 213 days (~18bn seconds) of simulated time.

**Comment by gunney1** [comment]
I would like to simulate a network where a milisecond is sufficient resolution, and nanosecond is overkill.  It'd be nice not to have to count off and disregard 6 zeros in the time values.  I saw that regardless of what resolution the user chooses, TimeLord a ns, us and ms time converters.  Would it break things to create these converters conditional on the user settings?  (Just throw the exception when these variables are accessed.)

**Comment by jjwilke** [comment]
A computer network? Or are you doing a quite different discrete event simulation?
1ms resolution will almost always be wildly inaccurate for most computer network simulations.

We could make the change (at the very least we should have added an error message that more sensibly said timebase minimum was 1ns).  It doesn't sound like this is a deal breaker, though, and you're still able to make progress in the meanwhile?

**Comment by gunney1** [comment]
It's a different discrete event simulation.  I can make progress in the mean time.  Thanks.
