### ISSUE TITLE
Multiple links on the same port not an error

### ISSUE THREAD

**Issue by jjwilke** [sstsimulator/sst-core#530]
If you create multiple links on the same ports this does not produce an error:

````
a = sst.Component(...)
b = sst.Component(...)
link = sst.Link("link1")
link.connect((a,"port0","10ns"),(b,"port0","10ns"))

link = sst.Link("link2")
link.connect((a,"port0","10ns"),(b,"port0","10ns"))
````

This code runs and produces an answer. 
This should at least be a warning - probably an error?

This doubling-up of links occurs in:
https://github.com/sstsimulator/sst-elements/blob/master/src/sst/elements/ariel/frontend/simple/examples/stream/ariel_snb_mlm.py

Related to sst-elements issue: https://github.com/sstsimulator/sst-elements/issues/1489

**Comment by feldergast** [comment]
I'll put in a check for this.  For now it will generate a warning.  In SST 11 it will generate an error.

**Comment by feldergast** [comment]
This now produces an error since PR #614
