### ISSUE TITLE
find_scoped_params

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#539]
Question: What does Params::find_scoped_params do and what is the difference between it and find_prefix_params.
I'm using SST-9.1
Thank you

**Comment by jjwilke** [comment]
most hierarchical parameters are stored as "X.Y.Z" or something like that. find_prefix_params required the delim "." to be included in the prefix:
```
auto X = find_prefix_params("X.")
```

For subtle reasons (and mostly to support another project) this was awkward so we added a `find_scoped_params` that only takes a prefix without the delim.
```
auto X = find_scoped_params("X")
```

This has always been a bit hacky and been largely replaced by nested and named subcomponents.
