### ISSUE TITLE
loadUserSubComponent incompatible with SimpleNetwork interfaces on SST 10.0.0

### ISSUE THREAD

**Issue by jleidel** [sstsimulator/sst-core#545]
`SST::BaseComponent::loadUserSubComponent` simple interface is not compatible with loading SimpleNetwork interfaces.  

In developing components outside the SST-Elements tree, we have found that loading components that inherit merlin parameters are not always compatible with the component load interfaces.  None of the simple interfaces appear to work.  

Loading a component using the following interface fails with a compilation error (see compilation error below): 
`Nic = loadUserSubComponent<SST::Interfaces::SimpleNetwork>("nic");`

The only way to circumvent the compilation error is to utilize the following: 
```
Nic = loadUserSubComponent<SST::Interfaces::SimpleNetwork>("nic",
                                                          ComponentInfo::SHARE_NONE,
                                                          1);
```

Even then, the component will **never** load from the python input script.  We've tried loading our own NIC, test_nic from Merlin and others.  It fails every time.  

Compilation errors:
```
In file included from /rev/sst/sst-10.0.0/include/sst/core/statapi/statengine.h:24:0,
                 from /rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:22,
                 from /rev/sst/sst-10.0.0/include/sst/core/component.h:19,
                 from RevCPU.h:19,
                 from RevCPU.cc:11:
/rev/sst/sst-10.0.0/include/sst/core/factory.h: In instantiation of ‘Base* SST::Factory::Create(const string&, SST::Params&, CtorArgs&& ...) [with Base = SST::Interfaces::SimpleNetwork; CtorArgs = {const long unsigned int&, SST::Params&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:576:18:   required from ‘T* SST::BaseComponent::loadUserSubComponentByIndex(const string&, int, int, ARGS ...) [with T = SST::Interfaces::SimpleNetwork; ARGS = {}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:493:54:   required from ‘T* SST::BaseComponent::loadUserSubComponent(const string&, uint64_t, ARGS ...) [with T = SST::Interfaces::SimpleNetwork; ARGS = {}; std::__cxx11::string = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]’
/rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:455:39:   required from ‘T* SST::BaseComponent::loadUserSubComponent(const string&) [with T = SST::Interfaces::SimpleNetwork; std::__cxx11::string = std::__cxx11::basic_string<char>]’
RevCPU.cc:89:69:   required from here
/rev/sst/sst-10.0.0/include/sst/core/factory.h:152:31: error: no matching function for call to ‘SST::ELI::Builder<SST::Interfaces::SimpleNetwork, long unsigned int, SST::Params&, int>::create(const long unsigned int&, SST::Params&)’
                         Base* ret = fact->create(std::forward<CtorArgs>(args)...);
                               ^~~
In file included from /rev/sst/sst-10.0.0/include/sst/core/eli/elementinfo.h:26:0,
                 from /rev/sst/sst-10.0.0/include/sst/core/statapi/statbase.h:22,
                 from /rev/sst/sst-10.0.0/include/sst/core/statapi/statengine.h:18,
                 from /rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:22,
                 from /rev/sst/sst-10.0.0/include/sst/core/component.h:19,
                 from RevCPU.h:19,
                 from RevCPU.cc:11:
/rev/sst/sst-10.0.0/include/sst/core/eli/elementbuilder.h:26:17: note: candidate: Base* SST::ELI::Builder<Base, Args>::create(Args ...) [with Base = SST::Interfaces::SimpleNetwork; Args = {long unsigned int, SST::Params&, int}]
   virtual Base* create(Args... ctorArgs) = 0;
                 ^~~~~~
/rev/sst/sst-10.0.0/include/sst/core/eli/elementbuilder.h:26:17: note:   candidate expects 3 arguments, 2 provided
```

**Comment by jjwilke** [comment]
Could you clarify what you mean by "never load from the python input script"?

**Comment by jleidel** [comment]
attempting to load the NIC interface using the prescribed setSubComponent methods in python fails to load.  

`comp_nic = comp_cpu.setSubComponent("nic","revcpu.RevNIC")`

**Comment by feldergast** [comment]
Not sure what’s going on here.  SimpleNetwork is used in many components throughout the element libraries, so we’ll need to find out what’s different here.

One thing to note, test_nic is not a SubComponent and does not implement the SimpleNetwork API, so would not be loadable.  If you can create a small replicator example and send it to me, that would be the best route.

At the very least, we’ll need information about the class you’re trying to load the SimpleMemory element into and the class you’re trying to load.  I hate errors from templated code, but the error below seems to be indicating that the class you’re trying to load doesn’t have a constructor with the right type signature.  Though I’m not sure why using the other version of loadUserSubComponent should get you through that issue.

The first thing to check would be to make sure the class you’re loading inherits from SimpleNetwork somewhere along the way (If you’re using Merlin routers, then this needs to be either merlin.linkcontol or merlin.reorderlinkcontrol).  It will also need to have a constructor with the following type signature:

(ComponentId_t cid, Params &params, int vns);

Next, you need to make sure that you have the proper slot definition in whatever Component/SubComponent you are loading the interface into.  The slot definition will need to declare SimpleNetwork as the type.  Something like:

SST_ELI_DOCUMENT_SUBCOMPONENT_SLOTS(
{"networkIF", "Network interface", "SST::Interfaces::SimpleNetwork" }
)

If all of these are in place, then the class should load with the commands you listed.

On Jul 24, 2020, at 9:09 AM, jleidel <notifications@github.com> wrote:

﻿

SST::BaseComponent::loadUserSubComponent simple interface is not compatible with loading SimpleNetwork interfaces.

In developing components outside the SST-Elements tree, we have found that loading components that inherit merlin parameters are not always compatible with the component load interfaces. None of the simple interfaces appear to work.

Loading a component using the following interface fails with a compilation error (see compilation error below):
Nic = loadUserSubComponent<SST::Interfaces::SimpleNetwork>("nic");

The only way to circumvent the compilation error is to utilize the following:

Nic = loadUserSubComponent<SST::Interfaces::SimpleNetwork>("nic",
                                                          ComponentInfo::SHARE_NONE,
                                                          1);


Even then, the component will never load from the python input script. We've tried loading our own NIC, test_nic from Merlin and others. It fails every time.

Compilation errors:

In file included from /rev/sst/sst-10.0.0/include/sst/core/statapi/statengine.h:24:0,
                 from /rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:22,
                 from /rev/sst/sst-10.0.0/include/sst/core/component.h:19,
                 from RevCPU.h:19,
                 from RevCPU.cc:11:
/rev/sst/sst-10.0.0/include/sst/core/factory.h: In instantiation of ‘Base* SST::Factory::Create(const string&, SST::Params&, CtorArgs&& ...) [with Base = SST::Interfaces::SimpleNetwork; CtorArgs = {const long unsigned int&, SST::Params&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:576:18:   required from ‘T* SST::BaseComponent::loadUserSubComponentByIndex(const string&, int, int, ARGS ...) [with T = SST::Interfaces::SimpleNetwork; ARGS = {}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:493:54:   required from ‘T* SST::BaseComponent::loadUserSubComponent(const string&, uint64_t, ARGS ...) [with T = SST::Interfaces::SimpleNetwork; ARGS = {}; std::__cxx11::string = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]’
/rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:455:39:   required from ‘T* SST::BaseComponent::loadUserSubComponent(const string&) [with T = SST::Interfaces::SimpleNetwork; std::__cxx11::string = std::__cxx11::basic_string<char>]’
RevCPU.cc:89:69:   required from here
/rev/sst/sst-10.0.0/include/sst/core/factory.h:152:31: error: no matching function for call to ‘SST::ELI::Builder<SST::Interfaces::SimpleNetwork, long unsigned int, SST::Params&, int>::create(const long unsigned int&, SST::Params&)’
                         Base* ret = fact->create(std::forward<CtorArgs>(args)...);
                               ^~~
In file included from /rev/sst/sst-10.0.0/include/sst/core/eli/elementinfo.h:26:0,
                 from /rev/sst/sst-10.0.0/include/sst/core/statapi/statbase.h:22,
                 from /rev/sst/sst-10.0.0/include/sst/core/statapi/statengine.h:18,
                 from /rev/sst/sst-10.0.0/include/sst/core/baseComponent.h:22,
                 from /rev/sst/sst-10.0.0/include/sst/core/component.h:19,
                 from RevCPU.h:19,
                 from RevCPU.cc:11:
/rev/sst/sst-10.0.0/include/sst/core/eli/elementbuilder.h:26:17: note: candidate: Base* SST::ELI::Builder<Base, Args>::create(Args ...) [with Base = SST::Interfaces::SimpleNetwork; Args = {long unsigned int, SST::Params&, int}]
   virtual Base* create(Args... ctorArgs) = 0;
                 ^~~~~~
/rev/sst/sst-10.0.0/include/sst/core/eli/elementbuilder.h:26:17: note:   candidate expects 3 arguments, 2 provided

**Comment by jleidel** [comment]
@feldergast, we're attempting to build in a simple NIC into a CPU component such that multiple CPUs can communicate using network packets (as opposed to memNIC and memHierarchy).  I'll push the code externally and post a link here.  As of now, the "NIC" class inherits from SST::Component.  The NIC includes a subComponent ("networkIF") that is of type SST::Interfaces::SimpleNetwork which represents the link interface to a merlin router.

**Comment by feldergast** [comment]
Normally only the SubComponents that interface directly to a network would implement SimpleNetwork.  What is RevNIC doing?  Does it actually need to implement SimpleNetwork, or does it just need to load a SimpleNetwork?

On Jul 24, 2020, at 9:33 AM, jleidel <notifications@github.com> wrote:

﻿

attempting to load the NIC interface using the prescribed setSubComponent methods in python fails to load.

comp_nic = comp_cpu.setSubComponent("nic","revcpu.RevNIC")

**Comment by jleidel** [comment]
@feldergast, the example code resides here: 
https://github.com/tactcomplabs/rev/tree/devel
Pull the devel branch.  
Example simulation script (which is currently broken) is in ~/test/ex3/

**Comment by feldergast** [comment]
Awesome, thanks. I’ll take a look.

Sent from my iPad

On Jul 24, 2020, at 9:47 AM, jleidel <notifications@github.com> wrote:

﻿

@feldergast<https://github.com/feldergast>, the example code resides here:
https://github.com/tactcomplabs/rev/tree/devel
Pull the devel branch.
Example simulation script (which is currently broken) is in ~/test/ex3/

**Comment by feldergast** [comment]
I’m only seeing ex1 and ex2 directories…

**Comment by jleidel** [comment]
I just pushed an update to the 'devel' tree.  Apologies... it had not
yet been added

**Comment by jjwilke** [comment]
For the load failure - what error output are you getting?

**Comment by jleidel** [comment]
I see the following: 
`FATAL: RevCPU[cpu:RevCPU:0]: Error: no NIC object loaded into RevCPU`

**Comment by jleidel** [comment]
> I see the following:
> `FATAL: RevCPU[cpu:RevCPU:0]: Error: no NIC object loaded into RevCPU`

This is propagated from line 88 of RevCPU.cc whereby the NIC object is null.

**Comment by jjwilke** [comment]
Huh. Okay. I don't think we have any code paths that return null. I would have expected you to get a crash from sst-core complaining about an unknown component type. I'll take a look as well.

**Comment by jjwilke** [comment]
````
        if ( isSubComponentLoadableUsingAPI<T>(sub_info->type) ) {
            auto ret = Factory::getFactory()->Create<T>(sub_info->type, myParams, sub_info->id, myParams, args...);
            return ret;
        }
        return nullptr;
````
This strikes me as a really bad idea. Was there a reason we return `nullptr` here instead of crashing with an error message?

**Comment by jjwilke** [comment]
Said another: why would we check if it's buildable instead of just trying to build it?

**Comment by jjwilke** [comment]
We have numerous problems converging here:
1. We should not have a nullptr return. This should just be trying to instantiate the NIC. Then you would get a load error that says "There is no subcomponent named ''X' registered under interface 'Y'"
2. Having gotten that error message...  The NIC does not inherit from SimpleNetwork and then is also not registered as matching the SimpleNetwork API.
3.  SimpleNetwork expects an integer argument in its constructor. I actually don't know what this is for - but hence the need for the extra argument.  You would need to modify the constructor of RevNIC.
4. RevNIC is a component, but will need to be a subcomponent that inherits from SimpleNetwork.

**Comment by feldergast** [comment]
There was a use case where you would try to load an “enhanced” API, but if that failed you could try to load a base API.  This case could be covered by calling the isSubComponentLoadableUsingAPI() to determine which version of loadUserSubComponent to call.  So, we should make sure the isSubComponentLoadableUsingAPI is a public (or protected if in BaseComponent) API and remove the check here.

Sent from my iPad

On Jul 24, 2020, at 11:13 AM, Jeremy <notifications@github.com> wrote:

﻿

        if ( isSubComponentLoadableUsingAPI<T>(sub_info->type) ) {
            auto ret = Factory::getFactory()->Create<T>(sub_info->type, myParams, sub_info->id, myParams, args...);
            return ret;
        }
        return nullptr;


This strikes me as a really bad idea. Was there a reason we return nullptr here instead of crashing with an error message?

**Comment by jjwilke** [comment]
Going a little further: Once you change `RevNIC` to inherit from `SimpleNetwork` instead of `Component` you'll get a slew of error messages about missing methods. Once you get those implemented, you should able to load the RevNIC as a SimpleNetwork.

**Comment by jjwilke** [comment]
And don't forget the registration, e.g. from elements:
````
    SST_ELI_REGISTER_SUBCOMPONENT_DERIVED(
        LinkControl,
        "kingsley",
        "linkcontrol",
        SST_ELI_ELEMENT_VERSION(0,1,0),
        "Link Control module for building Kingsley-enabled NICs",
        SST::Interfaces::SimpleNetwork)
````

**Comment by jjwilke** [comment]
Yeah, we should have different code paths for "recoverable failure" and "non-recoverable failure" where non-recoverable is the default.  We do the same for configuring links.  This keeps constantly coming up where people get meaningless segfaults because we made the default behavior the uncommon use case.

**Comment by jjwilke** [comment]
Or in this case a failed assert because you actually checked for nullptr : )

**Comment by feldergast** [comment]
I think that it may be time to start introducing exceptions into the core build code.  When we first wrote SST, we wanted to avoid exceptions because of the runtime overhead.  I think we still want to avoid exceptions for anything in the run loop, but for build code, exceptions would mean we don’t have to determine recoverable versus unrecoverable in the core.  The element developer could determine what they can recover from.  If they don’t check, an exception will be able to give a reasonable error message.

On Jul 24, 2020, at 11:34 AM, Jeremy <notifications@github.com> wrote:

﻿

Yeah, we should have different code paths for "recoverable failure" and "non-recoverable failure" where non-recoverable is the default. We do the same for configuring links. This keeps constantly coming up where people get meaningless segfaults because we made the default behavior the uncommon use case.

**Comment by jleidel** [comment]
> We have numerous problems converging here:
> 
> 1. We should not have a nullptr return. This should just be trying to instantiate the NIC. Then you would get a load error that says "There is no subcomponent named ''X' registered under interface 'Y'"
> 2. Having gotten that error message...  The NIC does not inherit from SimpleNetwork and then is also not registered as matching the SimpleNetwork API.
> 3. SimpleNetwork expects an integer argument in its constructor. I actually don't know what this is for - but hence the need for the extra argument.  You would need to modify the constructor of RevNIC.
> 4. RevNIC is a component, but will need to be a subcomponent that inherits from SimpleNetwork.

@gvoskuilen wrote up a good example of an external component that includes an internal NIC device.  I see where things went off the rails.  This is definitely a case where templated C++ constructors are rather prone to errors.  If at the least, the constructor routines could throw the exceptions as mentioned by @feldergast for components or subcomponents.  This overhead should only be incurred at simulation startup, so the overall performance degradation should be minimal (in theory).

**Comment by jjwilke** [comment]
Yeah, exceptions shouldn't really add overhead. And init/setup overhead probably isn't a big deal. We're not compiling with -fno-except, anyway.

**Comment by jleidel** [comment]
@jjwilke, do you want me to open a separate issue for the exception handling?  I believe I'm ready to close this bug.  I have the Rev model to the point where it will attempt to run.

**Comment by feldergast** [comment]
No, I'll add an issue once I work out the high level changes we want to make.  The issue is a little broader than just exceptions.

**Comment by jleidel** [comment]
@feldergast, sounds good.  closing this issue
