### ISSUE TITLE
Permissible use of ComponentExtension?

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#573]
New Issue for sst-core
----------------------
1 - What is the intended use for ComponentExtension?  I couldn't find sufficient documentation or any examples for its use, but I found it useful and want to make sure it won't go away.  Method BaseComponent::loadComponentExtension suggests that an extension shares the same component id as the parent component.  This suggests that the components can share more attributes such as names, time base, ports, event handlers, etc.

The way I use it now is that I have 2 component classes that are closely coupled.  They can talk to each other through links but for efficiency and to avoid the minimum unit latency of links, I'd like for one object to just call a method in the other object.  It would help that they have some of the same attributes.

**Comment by feldergast** [comment]
The ComponentExtension is still considered to be beta code, but the intent is to support it long term.  It is designed to do exactly what you described and whenever you make a call to a function in the BaseComponent API, it will act like it is the parent class.  It allows the library writer to break up the code into different classes to logically group functionality, but not have to worry about the limitations of using SubComponents.  There is s chance that some of the details of how it interacts with the parent component will change slightly, but it is unlikely to change in any dramatic ways.

Documentation is still forthcoming and will hopefully be included in SST 11.  Any bugs reported for this class will definitely be addressed.

**Comment by gunney1** [comment]
Very glad to hear that.  Thank you.

**Comment by kemstevens** [comment]
I was happy to see you all were intending to document this functionality in SST 11 but I did not find any in the release.  Would you please document ComponentExtension?  I am interested in using it.

**Comment by feldergast** [comment]
Please note that I didn't get time to put in the testing (or documentation) for ComponentExtensions for SST 11, so they are still considered beta.  However, at this point the API should be relatively stable (unless we find issues with more exhaustive testing).
