### ISSUE TITLE
Params::contains requires mutable object

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#582]
It looks like I can't check whether a Params contains a certain field if the Params is const.  I can work around this by getting all the keys using Params::getKeys() and looking for the key there, but I'm wondering if Params::contains could easily be made const.  Can it be done?  Using SST-10.  Thanks.

**Comment by feldergast** [comment]
Yes, contains() should be const.  I'll fix it in the next core pull request we put in.

**Comment by gunney1** [comment]
Thanks.

**Comment by feldergast** [comment]
Going to reopen so it can be tracked to completion.

**Comment by feldergast** [comment]
Two functions need to be marked const:

Params::count()
Params::contains()

**Comment by feldergast** [comment]
Fixed in #585
