### ISSUE TITLE
Can you make getDefaultTimeBase const?

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#610]
Any reason why getDefaultTimeBase isn't const?  Can you make it const?  It could return a const TimerConverter* instead of a mutable one.  I just want to access the converter factor while making it obvious that the component state doesn't change.

**Comment by feldergast** [comment]
That can be added. TimeConverters aren't really mutable objects anyway (no public mutator functions), so every function that returns them should probably return a const.

**Comment by feldergast** [comment]
I added a const version of getDefaultTimeBase() to both BaseComponent and Link.  I couldn't change the existing one without breaking compatibility with existing code.  I'll close this issue once the code is merged.

**Comment by feldergast** [comment]
Addressed in PR #621
