### ISSUE TITLE
Enhance configure script to check compiler version

### ISSUE THREAD

**Issue by mikepfrank** [sstsimulator/sst-core#62]
Arrange for the configure script to check the compiler version, in the case of known compilers (e.g., gcc, Intel cc) to make sure that is a new enough version to compile SST successfully.  In the case of an older, unsupported compiler version, report an error and halt configuration.

**Comment by mikepfrank** [comment]
Alternatively, check specifically for needed features that might be missing from older compilers that users are likely to try.

**Comment by nmhamster** [comment]
@mikepfrank - what specific feature didn't compile for you, we should go through these one by one because some compilers (e.g. GCC on RHEL) are patched so they can provide most of what we need.

**Comment by nmhamster** [comment]
This is now active since SST 7.0.
