### ISSUE TITLE
addParams

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-core#622]
[Feature Request]

Configuration of simulators is notoriously error prone. The SST configuration system forces the user to specify the configuration knobs for each component. These knobs are available to be set using addParam and addParams. Neither of these functions provides any name checking. This causes problems when a component programmer removes a parameter but the python scripts never get updated. This also causes problems when the python user has a typo in the name. 

Would it be feasible to add a check to addParam and addParams to ensure the name actually exists as a registered component parameter name?

**Comment by feldergast** [comment]
This is already a planned feature and should be starting to phase in between SST 11 and SST 11.1.  It is planned to be fully enabled by SST 12.

**Comment by nicmcd** [comment]
Very cool! Is there a list of planned features for future releases?

**Comment by nicmcd** [comment]
I would also suggest not forcing the user to specify the default valid twice. Allow the params.find function to retrieve the default that is already specified by the SST_ELI_DOCUMENT_PARAMS macro.

**Comment by feldergast** [comment]
Also planned as part of the Params rework.  Not sure what the final timeline is, but probably won't be fully enabled until SST 13 because of the requirement to maintain backward compatibility for at least one major release cycle.
