### ISSUE TITLE
Define bounds of SSTRandom nextUniform

### ISSUE THREAD

**Issue by nicmcd** [sstsimulator/sst-core#629]
https://github.com/sstsimulator/sst-core/blob/9ee1db28c6c45129f685179e086739b9d3df83ea/src/sst/core/rng/sstrng.h#L31

Please define whether or not 0 and 1 are included in the bounds of SST::SSTRandrom::nextUniform(). STL uses [0,1) by default which is very convent for selecting and random index in an array/vector:
```
size_t index = rng.nextUniform() * values.size();
```
Is this the case in SST? It is checked in the unit tests of the RNG implementations?

**Comment by nmhamster** [comment]
See proposed changes in PR #657

**Comment by nmhamster** [comment]
@nicmcd - confirmed, SST provided RNG operate in the range `[0,1)` as requested. Please reopen this issue if you experienced issues. Documentation is updated.
