### ISSUE TITLE
The pymodel infrastructure does not have a way to get number of threads

### ISSUE THREAD

**Issue by feldergast** [sstsimulator/sst-core#63]

**Comment by nmhamster** [comment]
It looks like this is in `pymodel.cc` (`getNumThreads()`). Is this just a version of SST issue?

**Comment by feldergast** [comment]
Should have been more specific.  You can get the number of threads by first calling getProgramOptions() and then getting numThreads out of the dictionary that's returned.  We should add a getThreadCount() directly to the SST python module (to complement the getMPIRankCount() that is already there.

**Comment by bjmoor** [comment]
Should be fixed with PR #99
