### ISSUE TITLE
Error during configuration step

### ISSUE THREAD

**Issue by jesunsahariar** [sstsimulator/sst-core#645]
1 - Detailed description of problem or enhancement
Hi,
I am trying to configure and install sst-core on a centOS machine and currently receiving the following error (or somewhat similar error, depending on the python version) during the configuration step. I am also aware of the requirement that ".. On RedHat Linux type systems (including CentOS) you must also install the libtool-ltdl-devel package. This will provide the file COPYING.LIB needed by libtool." 

Would greatly appreciate any feedback. Please let me know if I can provide any additional information. Thanks!

```
"configure:19413: error: Unable to locate Python library python3.7m in -L/share/apps/python/anaconda3-2020.02/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/share/apps/python/anaco\
nda3-2020.02/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lrt -lm   -L/share/apps/python/anaconda3-2020.02/lib -L/share/apps/python/anaconda3-2020.02/lib64"
```
2 - Describe how to reproduce
Modules loaded:

`gcc/8.2.0, openmpi/3.1.3, cmake/3.18.2, python/anaconda3.2020.02 (unsuccessfully tried other versions of python 3 too)`

Then I ran the following commands:
```
git clone git@github.com:sstsimulator/sst-core.git
export SST_CORE_HOME=...
export SST_CORE_ROOT=..

./autogen.sh

./configure CXX=mpicxx CC=mpicc --prefix=$SST_CORE_HOME

or 

./configure  --prefix=$SST_CORE_HOME
```
3 - What Operating system(s) and versions 

```cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
4 - What version of external libraries (Boost, MPI)
Modules loaded:
`gcc/8.2.0, openmpi/3.1.3, cmake/3.18.2, python/anaconda3.2020.02 (unsuccessfully tried other versions of python 3 too)`
The autotools versions are also compatible with the recommendation on the SST simulator website.

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
Cloned the latest sst-core repo, sha1: b4cfcd9baa1d948020dff3cc50227d5d4021d9b3

**Comment by nmhamster** [comment]
Hey @jesunsahariar - hmmm, this is weird. Can you just try running:

1. `python3-config --libs` (or if python3-config not found, can you try `python-config --libs`)
2. `which python3-config
3. `which python3`
4. `grep python3-config config.log`

If you can post those outputs it would be good.

**Comment by jesunsahariar** [comment]
Hi Simon,

Thank you very much for your reply. Here are the outputs from the commands you suggested:
```
python3-config --libs
-lpython3.7m -lcrypt -lpthread -ldl  -lutil -lrt -lm
```
```
which python3-config
/share/apps/python/anaconda3-2020.02/bin/python3-config
```
```
which python3
/share/apps/python/anaconda3-2020.02/bin/python
```
```
grep python3-config config.log
configure:21108: checking for python3-config
configure:21126: found /share/apps/python/anaconda3-2020.02/bin/python3-config
configure:21138: result: /share/apps/python/anaconda3-2020.02/bin/python3-config
ac_cv_path_pycfg=/share/apps/python/anaconda3-2020.02/bin/python3-config
pycfg='/share/apps/python/anaconda3-2020.02/bin/python3-config'
```

Please let me know if I can provide any additional information. Thanks again for your time to look into this issue.

--Jesun

**Comment by nmhamster** [comment]
@jesunsahariar - this looks good which is even more weird!

Can I ask you to run some a directory listings, something like:

1. `ls -al /share/apps/python/anaconda3-2020.02/lib64`
2. `ls -al /share/apps/python/anaconda3-2020.02/lib`
3. 'ls -al /share/apps/python/anaconda3-2020.02/lib/python3.7/config-3.7m-x86_64-linux-gnu`

We are trying to check the `libpython3.7m.so` or `libpython3.7m.a` exist and that the permissions are good on the library for you to access them.

**Comment by jesunsahariar** [comment]
Hi Simon,

Thank you very much for the suggestions. I ran the directory listings and explicitly looked for the two libraries you suggested (since the whole directory listing was a little bit longer :-) )

```
pwd
/share/apps/python/anaconda3-2020.02
```
```
find . -name libpython3.7m.so
./lib/libpython3.7m.so
```
```
ls -al ./lib/libpython3.7m.so
lrwxrwxrwx 1 nobody nobody 20 Aug  7  2020 ./lib/libpython3.7m.so -> libpython3.7m.so.1.0
```
```
find . -name libpython3.7m.a
./lib/libpython3.7m.a
```
```
ls -al ./lib/libpython3.7m.a
-rwxrwxr-x 1 nobody nobody 26668358 Aug  7  2020 ./lib/libpython3.7m.a
```

For the last command, here is the output
```
ls -al /share/apps/python/anaconda3-2020.02/lib/python3.7/config-3.7m-x86_64-linux-gnu
```
![image](https://user-images.githubusercontent.com/13543936/118692577-13937700-b7bf-11eb-9d49-01a4bcb19b8f.png)

Please let me know whether still the whole directory listing would be more helpful.

Thank you!

**Comment by allevin** [comment]
@jesunsahariar 

- Just to make sure, you recently cloned the devel branch of sst-core?  Earlier versions of SST were configured to prefer Python2
- Can you send us/attach your config.log file so we can review it.
- Can you also do a quick test of:
   - `which python`
   - `which python2`
   - `which python-config`
   - `which python2-config` 
- you may want to try `./configure  --prefix=$SST_CORE_HOME --with-python=<path to python3-config>`

**Comment by jesunsahariar** [comment]
Hi Aaron,

Thank you for your reply.

- I cloned the current master branch.

[config_with_cc.log](https://github.com/sstsimulator/sst-core/files/6503495/config_with_cc.log)
[config_with_no_cc.log](https://github.com/sstsimulator/sst-core/files/6503496/config_with_no_cc.log)

``` 
which python
/share/apps/python/anaconda3-2020.02/bin/python
```
```
 which python2
/usr/bin/python2
``` 
```
which python-config
/usr/bin/python-config
```

``` 
which python2-config
/usr/bin/python2-config
```

The log files are attached. Please let me know if I can be of any help. Thank you!
--Jesun

**Comment by nmhamster** [comment]
The error is in your `config.log`. See below. It looks like you compiled with LTO enabled using an older GCC/different GCC compiler than the one you are using now. This is an issue with your Python installation. You can either recompile with the same compiler or compile Python with LTO enabled.

```
configure:19994: mpicxx -o conftest -g -O2 -std=c++1y -D__STDC_FORMAT_MACROS -Wall -Wextra -I/share/apps/python/anaconda3-2020.02/include/python3.7m -I/share/apps/python/anaconda3-2020.02/include/python3.7m -I$(top_builddir) -I$(top_srcdir)/src -I$(top_builddir)/src  -L/share/apps/python/anaconda3-2020.02/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/share/apps/python/anaconda3-2020.02/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lrt -lm   -L/share/apps/python/anaconda3-2020.02/lib -L/share/apps/python/anaconda3-2020.02/lib64 conftest.cpp -lpython3.7m  -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lrt -lm   >&5
lto1: fatal error: bytecode stream in file '/share/apps/python/anaconda3-2020.02/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a' generated with LTO version 6.0 instead of the expected 7.0
```

**Comment by jesunsahariar** [comment]
Hi Simon,

Thank you very much for the awesome pointer to the error :-) . Really appreciate your help. Seems like `gcc 7.1.0` in conjunction with `python/anaconda3.2020.02` is the right combination to use. I did that and everything worked perfectly.
Thank you and Aaron for your help and for your time!
