### ISSUE TITLE
clangformat declaration file broken for pre clang-11 builds

### ISSUE THREAD

**Issue by jleidel** [sstsimulator/sst-core#650]
**Summary**
The `.clang-format` file used for proper syntax formatting found in the `devel` branch of sst-core is currently broken for versions of `clang-format` prior to version 11 (et. al. LLVM/Clang Version 11).  There are a number of formatting macros that were introduced in Clang-11 found in the format file that do not function with `clang-format` version 10.  There are also a number of macros that are not functional in releases prior to 11, but are also not applicable to C/CXX.  I'll summarize the issue details as follows: 

**Configuration:**
- Ubuntu 20.04LTS
- clang version 10.0.0-4ubuntu1 (installed from llvm apt-repo)
- clang-format version 10.0.0-4ubuntu1
- `clang-format --dry-run /path/to/source.cc`

**Macros Causing Issues**
- AlignConsecutiveBitFields (requires clang-11)
- AllowShortEnumsOnASingleLine (requires clang-11)
- AttributeMacros (requires clang-11)
- BeforeLambdaBody (requires clang-11)
- BeforeWhile (requires clang-11)
- IndentCaseBlocks (requires clang-11)
- IndentExternBlock (requires clang-11)
- SpaceAroundPointerQualifiers (requires clang-11)
- BitFieldColonSpacing (requires clang-11)
- WhitespaceSensitiveMacros (requires clang-11)
- InsertTrailingCommas (clang-11 and Java-specific)
- ObjCBreakBeforeNestedBlockParam (clang-11 and ObjC-specific)
- SortJavaStaticImport (clang-11 and Java-specific)

**Potential Fixes**
I have a patch that comments out the erroneous options such that the build functions in clang-10.  However, we need to decide what minimum version of clang will be used to format the code.  If clang-11 is available for formatting on all standard build systems, then the answer is to permit the use of clang-11 formatting macros.  However, if that is not the case, then we need to ensure that we provide some notional backward compatibility for older versions of clang.  At which point, we need to define how far back we support in terms of the clang-format macros.

**Comment by feldergast** [comment]
@jleidel We think it's entirely fine to tie things to clang-11+.  It may not be available on all build systems, but it will be available on enough that we're comfortable with this requirement.  In practice, we'll only run the check on one test machine when we test PRs, and we can make sure it has a compatible version.  Also, we're not worried about any formatting that doesn't apply to c/c++.

**Comment by jleidel** [comment]
@feldergast, thanks for the update.  I'll retest with clang-11 on our systems and ensure things are stable before closing the issue.

**Comment by jleidel** [comment]
Using clang-format-11, there are 5 remaining issues in the .clang-format configuration.  I originally thought these features made it into clang-11 (based upon their review dates in Phabricator), but apparently they were held for clang-12.  The list includes: 

* AttributeMacros
* SortJavaStaticImport (we can probably ignore this one that it is Java-centric)
* SpaceAroundPointerQualifiers
* BitFieldColonSpacing

If everyone is ok using clang-12 moving forward for source linting then I'll close this Issue

**Comment by jleidel** [comment]
There is also one remaining bug in the clang format file that requires a patch.  I will open a separate issue and submit a PR

**Comment by jleidel** [comment]
I believe I can close this now as clang-format is working well with clang-format-12
