### ISSUE TITLE
memory ownership in objectComms.h

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#664]
In objectComms.h there are several `char* buffer = new char[size];` calls.  It is unclear if these are ever deleted? If they are deleted then `deserialize(std::vector<char> &buffer)` in the same file probably has a double delete.  I'd suggest that we switch away from using new if at all possible, but my main goal is just to figure out what is going on.

**Comment by feldergast** [comment]
I'll take a look.  There clearly isn't a double delete in any path we use today or we would have seen it by now, but I'll track down what's happening.

**Comment by calewis** [comment]
@feldergast any updates? I can look into this if needed.
