### ISSUE TITLE
Clang format script isn't working

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#671]
Clang format script isn't working 

RHEL7

Last commit from upstream core is 98803c0026ae8c7d925dfd0e085ef102d8107077

I'm in the top level directory and I try to run 
```
$ scripts/clang-format-test.sh
Failed to execute process 'scripts/clang-format-test.sh'. Reason:
exec: Exec format error
The file 'scripts/clang-format-test.sh' is marked as an executable but could not be run by the operating system.
```

**Comment by feldergast** [comment]
Looks like it's missing #!/bin/bash or #!/usr/bin/env bash
