### ISSUE TITLE
Missing include in timeConverter.hpp

### ISSUE THREAD

**Issue by gunney1** [sstsimulator/sst-core#675]
In SST-11.0.0, timeConverter.hpp is missing an include:
#include "sst/core/unitAlgebra.h"
needed for the UnitAlgebra getPeriod() delcaration.

**Comment by feldergast** [comment]
I have this change already in a branch I'm working on.  Should be ready to be merged in the next day or so.

**Comment by calewis** [comment]
@feldergast did this pr make it in yet?

**Comment by feldergast** [comment]
Fixed in PR #677
