### ISSUE TITLE
Make distcheck is failing 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#685]
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement
```
ERROR: files left in build directory after distclean:
./src/sst/core/libltdl/.deps/lt__strl.Plo
```

2 - Describe how to reproduce
I haven't tested this with a user provided libltdl
```
run make distcheck
```

3 - What Operating system(s) and versions 
RHEL 7.9, gcc 10.3, autoconf 2.69

4 - What version of external libraries (Boost, MPI)
Openmpi 4.0.4

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

Seen on multiple branches of core

**Comment by calewis** [comment]
I don't think make dist is actually broken, it appears that cleanup is just missing a file.

**Comment by berquist** [comment]
I can't reproduce this on Rocky 8 with (system) GCC 8.5.0, OpenMPI 4.1.5, `autoconf@2.69`, `automake@1.16.5`, `gmake@4.4.1` at 3c22b629b306f7ec7a7f46cb2051a79b9971e8a3.
