### ISSUE TITLE
Can't delete files after make distcheck 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#686]
RHEL 7.9, recent branch off of devel. 
```
$ make distcheck 
 ... many lines 

$ ls
config.log  config.status  doc  external  libtool  Makefile  share  src  sstcore--dev  sst_test_outputs

$ rm -rf sstcore-dev
rm: cannot remove ‘sstcore--dev/ISSUES’: Permission denied
rm: cannot remove ‘sstcore--dev/_build’: Permission denied
rm: cannot remove ‘sstcore--dev/src/Makefile.am’: Permission denied
...

$ ls -lh 
...
dr-xr-xr-x. 11 calewis calewis 4.0K Aug  3 10:01 sstcore--dev
...
```

**Comment by calewis** [comment]
@allevin I assigned you, but if you are not the right person just change it.

**Comment by allevin** [comment]
@calewis I didn't even know we had a build target called distcheck.  We don't do any testing with this.  Is this still important if CMake is going to move forward?  i.e. is it worth spending time on an issue that we dont test or anyone uses (that we know of)?

**Comment by calewis** [comment]
We still have a year at least of using autotools.

**Comment by berquist** [comment]
I can't reproduce this on Rocky 8 with (system) GCC 8.5.0, OpenMPI 4.1.5, `autoconf@2.69`, `automake@1.16.5`, `gmake@4.4.1` at 3c22b629b306f7ec7a7f46cb2051a79b9971e8a3.  There are no problems with `git clean -xdf .` for the in-source build.
