### ISSUE TITLE
error during sstcore configure

### ISSUE THREAD

**Issue by ErsinCK** [sstsimulator/sst-core#727]
New Issue for sst-core
----------------------

http://sst-simulator.org/SSTPages/SSTBuildAndInstall_11dot0dot0_SeriesDetailedBuildInstructions/

I am using this to install OpenMPI and sstcore.

OpenMPI is installed succesfully. In fact, I compiled some programs with it and can confirm that it works.

during installation of sstcore, I am using ./configure --prefix=$SST_CORE_HOME and the configuration gives the following error.

checking c_asm.h usability... no
checking c_asm.h presence... no
checking for c_asm.h... no
checking for dlfcn.h... (cached) yes
checking intrinsics.h usability... no
checking intrinsics.h presence... no
checking for intrinsics.h... no
checking mach/mach_time.h usability... no
checking mach/mach_time.h presence... no
checking for mach/mach_time.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/types.h... (cached) yes
checking for unistd.h... (cached) yes
checking for doxygen... no
checking for Mac OSX... no
checking for mpicc... no
checking for hcc... no
checking for mpxlc_r... no
checking for mpxlc... no
checking for mpcc... no
checking for cmpicc... no
checking how to run the MPI C preprocessor... gcc -E
checking for MPI_Init... no
checking for MPI_Init in -lmpi... no
checking for MPI_Init in -lmpich... no
configure: error: Could not find MPI package

Why can't it find MPI package? everything is done as you describe on the webpage linked at the top. I am using Ubuntu 18.04
with gcc 7.5. Is gcc version the problem?

Thanks for the help!

**Comment by nmhamster** [comment]
@ErsinCK - can you look in the config.log file which is generated when `./configure` runs (it will be in the same directory). There should be some operations to check for MPI in there, these will fail. Can you copy that into your issue or attach your config.log file so we can help you? Thanks for reporting the issue.

**Comment by ErsinCK** [comment]
Sorry about the late response. I was using it without the openmpi. I might not even need it but this could be useful for other people interested. I reinstalled to recreate the error.

[config.log](https://github.com/sstsimulator/sst-core/files/7178431/config.log)

**Comment by nmhamster** [comment]
@ErsinCK - the `config.log` correctly states that `-lmpi` cannot be found. This will be the case if you do not have an MPI variant installed (e.g. MPICH, MVAPICH, OpenMPI etc). 

You can proceed without using MPI in the core by specifying `--disable-mpi`, this will build a single-node version of the code. If you want to use the distributed (parallel) event core, which we generally recommend, then you should install an MPI version and you need `mpicc` and `mpicxx` to be in your `PATH` for the configure to pick these up correctly. 

Does that help with your question?

**Comment by berquist** [comment]
There was never a response from the original poster and the `config.log` looks as expected if MPI isn't available via the requisite environment variables.  (If OpenMPI was installed via `apt`, then there is an actual bug somewhere, since that should require no extra work with paths.)
