### ISSUE TITLE
Macro testing requires using names reserved for sst-elements

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#729]
Currently in macro we have 
```
sst-register SST_ELEMENT_SOURCE sst-macro=$(abs_srcdir)/../..
sst-register SST_ELEMENT_TESTS sst-macro=$(abs_srcdir)/../../tests
```
Which we really shouldn't have since these names are for the elements.  But if we remove these calls the autotester fails because it depends on this for finding the tests.

**Comment by nmhamster** [comment]
@calewis - I think we can to the conclusion that these were required. The bit which was missing was registering the SST_MACRO_LIBDIR setting. For example:

```
$ sst-register SST_MACRO SST_MACRO_LIBDIR=<path to the install/lib directory>
```

**Comment by calewis** [comment]
@nmhamster the following build failed the autotester https://github.com/sstsimulator/sst-macro/pull/641/commits/d148aa355e75584df4d58110ce06f6d70a669614

So I did the step of 
```
sst-register SST_MACRO SST_MACRO_LIBDIR=<path to the install/lib directory>
```
but that build didn't pass testing. I made this issue here because long term we don't want macro to have to use 
```
sst-register SST_ELEMENT_SOURCE sst-macro=$(abs_srcdir)/../..
sst-register SST_ELEMENT_TESTS sst-macro=$(abs_srcdir)/../../tests
```
Or do we?

**Comment by nmhamster** [comment]
@calewis - what is the failure mode for the build? I **think** we should have all the components (including Macro) register the same way so its consistent. Thoughts on that?

**Comment by calewis** [comment]
The failure is that the Jenkin's job can't find the tests because they aren't part of the `SST_ELEMENT_TESTS` paths.

**Comment by feldergast** [comment]
> @calewis - what is the failure mode for the build? I **think** we should have all the components (including Macro) register the same way so its consistent. Thoughts on that?

Looking at this some more, it’s probably okay to use the same sections for elements and macros.  It will just add another entry for the macro library to the list of all the other elements.

**Comment by jpkenny** [comment]
@nmhamster just clarifying on Drew's comment, macro will run fine if we register it as SST_MACRO, but the Jenkins testing relies on it being in SST_ELEMENTS so the *automated testing* will fail. Probably just means an update to bamboo.sh to do it better, but seems like nobody wants to touch bamboo.sh. Current situation works ok, just less than elegant.

**Comment by gvoskuilen** [comment]
I believe the test frameworks treats all elements the same whether they are part of "sst-elements" or not, hence the naming. This is the same way other external elements are registered too (with SST_ELEMENT_SOURCE and SST_ELEMNT_TESTS). I'd have to dig a bit but I think this is the way the frameworks operates, not related to bamboo.

**Comment by gvoskuilen** [comment]
@nmhamster Yes, that is right. 

In detail: 
- The SST_ELEMENT_TESTS registration is used by sst-test-elements to locate tests
- The SST_ELEMENT_SOURCE registration is also used in testing, although I'm not certain where specifically it gets used
- The element-specific registration is used by SST itself to locate libraries for simulation

**Comment by calewis** [comment]
So this is actually a non-issue?

**Comment by jpkenny** [comment]
It functions as intended. Macro components are functionally more or less elements and Mercury components will *be* elements. So I guess I lean towards "not broken, close issue".

**Comment by allevin** [comment]
@calewis @jpkenny @nmhamster @gvoskuilen is correct, the test frameworks can either test Core or Elements.   Elements must perform a registration of where their tests live (SST_ELEMENT_TESTS ) so that the test frameworks can find them.  Since we were registering the path to the tests, I also added the path to the source (SST_ELEMENT_SOURCE) just in case.  I cant recall if we use it however for anything.   As far as the frameworks is concerned, Macro is just another element that uses the Core.  NOTE: The Macro version that has its own core is tested using the old bash based test system.   Both test systems (old bash tests or new frameworks tests) are launched by the bamboo script for Jenkins testing.    The difference is that the new test frameworks can be run on the developers system once they after they "make install" the Core.
