### ISSUE TITLE
Fix GCC-10 warnings

### ISSUE THREAD

**Issue by pdbj** [sstsimulator/sst-core#736]
When compiling with GCC-10 (10.2.1 and 10.3 on two different systems) I encountered a number of minor warnings, all fixed by this patch.  This is based on v11.0.0_FINAL
[0001-Fix-GCC10-compilation-warnings.patch.txt](https://github.com/sstsimulator/sst-core/files/7324887/0001-Fix-GCC10-compilation-warnings.patch.txt)
.

**Comment by pdbj** [comment]
Just following up on some of the changes in the patch above:

Language standard: as of 2022-02-23 the build issues `-std=c++1y`, the pre-final label for C++-14. The code also uses `alignas` in a few places, and newer GCC complains that requires `-faligned-new` (or higher language standard).  So there is some sort of conflict there.

Incidentally, configure puts any user-provided CXXFLAGS _before_ the built ins, so it's not easy to change the language standard and see what happens.

`// fallthrough` is a GNU extension, so not portable.  `[[fallthrough]]` from C++17 _is_ portable

Presumably fixing the mismatched types in serialize_X are not problematic?

**Comment by pdbj** [comment]
[Here](https://github.com/pdbj/sst-core/commit/5fd54f67acf2d2481c5a1905cd26bb6f09bbc4ae) is an additional patch to fix type and width mismatches. (It also a few `[[fallthrough]]` and `[[maybe_unused]]` you can ignore.)

**Comment by pdbj** [comment]
Revised and broken out by issue:

* [Tag or remove possibly unused vars](https://github.com/pdbj/sst-core/commit/3159d03bbddfeb297d50c89a6be331eb539f0fbd)
* [Label `[[fallthrough]]` case](https://github.com/pdbj/sst-core/commit/b719e3c3b60b7ff0c20d6a647f3cee9a72e082e4)
* [[Fix c'tor initializers missing, not in declaration order](https://github.com/pdbj/sst-core/commit/31ea6a5b1d0650fd9dc3b3423be8e1acae3e4c87)
* [Fix typos in comments](https://github.com/pdbj/sst-core/commit/f30919d90a7a0e53c79c2a560682fd10509e5825)
* [Rename local var not to hide class data member](https://github.com/pdbj/sst-core/commit/08ee20c1f1e1b621a3b4e7eec2f94bf279e365fa)

**Comment by pdbj** [comment]
Rebased

- [Tag or remove possibly unused vars](https://github.com/pdbj/sst-core/commit/f5fe375f3225383dc04c858a98fca8290b87ec09)
- [Label [[fallthrough]] case](https://github.com/pdbj/sst-core/commit/56a1961a49eed304dc008880e259919a6e4f2ae6)
- [Fix c'tor initializers missing, not in declaration order](https://github.com/pdbj/sst-core/commit/7c4dc92390433e1deb72fcc2554dc35121746bdf)
- [Fix typos in comments](https://github.com/pdbj/sst-core/commit/7c546cd967fe97c743142d57cd892a41ac52b971)
- [Rename local var not to hide class data member](https://github.com/pdbj/sst-core/commit/cf146e28882eb5cf22b8d4dbf4c971f82017c169)

**Comment by berquist** [comment]
Done in #960.
