### ISSUE TITLE
test-sst-core uses wrong Python on Ubuntu 20.04

### ISSUE THREAD

**Issue by jwilso** [sstsimulator/sst-core#758]
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement
Because Ubuntu 20.04 uses only Python3 by default, there is no 'python' executable available, it must be explicitly invoked as 'python3'. sst-test-core looks for 'python', and fails if it is not found.

2 - Describe how to reproduce the issue
Run sst-test-core on Ubuntu 20.04 in default configuration.

3 - What Operating system(s) and versions 
Linux, Ubuntu 20.04

4 - What version of external libraries (Boost, MPI)
N/A

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
SST Release 11.0

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by berquist** [comment]
This seems to have been fixed around the time of #683 and works fine with the latest version.
