### ISSUE TITLE
boost -mt lib support dissappeared

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#76]
With the new autoconf setup, the support for auto-detecting the '-mt' variants of MacPort's Boost implementations has disappeared.  (ie, 'libboost_serialization-mt.dylib)   `./configure` passes, which suggests that our autoconf macro for BOOST does not actually attempt a library-test, only a header-test.

**Comment by nmhamster** [comment]
Yes this has been simplified for the initial version. We are slowly going to be adding these back.

**Comment by nmhamster** [comment]
Fixed and merged in #93 by @bjmoor.
