### ISSUE TITLE
How to estimate power consumption of a cpu or other elements in SST?

### ISSUE THREAD

**Issue by TOMsworkspace** [sstsimulator/sst-core#764]

**Comment by jleidel** [comment]
Tom, any notional power estimation will be done by the respective component-level implementations, not the SST-Core.  The Core is event handling mechanism and the resource broker for any respective simulation.  The individual components will need to have specific knowledge of the power required to operate any specific events.  

What specifically do you seek to achieve?

**Comment by TOMsworkspace** [comment]
I want to estimate the power/space on the re-designed MMU(based on SST Samba element). Bbut I do not know how to achieve this goal?

**Comment by jleidel** [comment]
In that case, I would suggest moving this PR over to the SST-Elements repo (where Samba resides).

**Comment by TOMsworkspace** [comment]
Ok, thanks.
