### ISSUE TITLE
Parallel JSON Writer Aborts Without File Extension

### ISSUE THREAD

**Issue by jleidel** [sstsimulator/sst-core#769]
When attempting to output parallel JSON simulation files from a python input file, the simulation aborts due to a std::out_of_range exception if the target JSON file name does not contain a file extension.  EG, using `OUTPUT_FOO` instead of `OUTPUT_FOO.json` will trigger the abort.

Its fairly simple to trigger it using existing examples.  This triggers the abort:
```
mpirun --hostfile output.txt -n 4 sst -v --output-json=fattree_256_test_parallel --parallel-output=1 fattree_256_test.py
```

This works:
```
mpirun --hostfile output.txt -n 4 sst -v --output-json=fattree_256_test_parallel.json --parallel-output=1 fattree_256_test.py
```

Error generated:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 92)
```

Ideally, we should catch this when parsing the file name and fail gracefully.  Feel free to assign this to me.

**Comment by feldergast** [comment]
This is a bigger issue with how we parse filenames.  We assume an extension exists.  I know right where this error is happening.  Let me take a look and see if I can fix it across the board.  I've got some other minor changes I'm working on and can add this to it.

**Comment by jleidel** [comment]
confirmed fix; closing
