### ISSUE TITLE
JSON Writer Generates Erroneous Link Configurations

### ISSUE THREAD

**Issue by jleidel** [sstsimulator/sst-core#770]
The current JSON writer code appears to be broken.  When we attempt to ingest a sample python script and output it back out as a json file, the link configuration fails.  We can successfully ingest a python script and output it as a python script that can be run.  

This works:
```
sst -v --output-config=foo.py ~/sst-core/tests/test_Component.py
sst -v foo.py
```

This is broken:
```
sst -v --output-json=foo.json ~/sst-core/tests/test_Component.py
sst -v foo.json
```

Trace:
```
FATAL:  SST Core: ERROR: Port Elink of Component c1.0 connected to two links: link_s_1_2, link_s_0_1.
SST Fatal Backtrace Information:
    0 : sst(_ZNK3SST6Output5fatalEjPKcS2_iS2_z+0x409) [0x555555674039]
    1 : sst(_ZNK3SST15ConfigComponent10checkPortsEv+0x270) [0x5555556459b0]
    2 : sst(_ZN3SST11ConfigGraph24checkForStructuralErrorsEv+0x10c) [0x5555556467cc]
    3 : sst(main+0x710) [0x555555605d00]
    4 : /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x1555535d6bf7]
    5 : sst(_start+0x2a) [0x55555561a0ea]
```

Broken starting with commit: 8c1afe458a4b9459258969189a0391ec8b5032c3

**Comment by feldergast** [comment]
I get the same error when running the commands above. However, looking at the created JSON output file, the file appears to be correct.  The issue must be in the reader.  Here's the JSON for the two links:

    {
      "name": "link_s_1_2",
      "left": {
        "component": "c1.0",
        "port": "Elink",
        "latency": "10000ps"
      },
      "right": {
        "component": "c2.0",
        "port": "Wlink",
        "latency": "10000ps"
      }
    },

    {
      "name": "link_s_0_1",
      "left": {
        "component": "c0.0",
        "port": "Elink",
        "latency": "10000ps"
      },
      "right": {
        "component": "c1.0",
        "port": "Wlink",
        "latency": "10000ps"
      }
    },

**Comment by feldergast** [comment]
Found the issue.  I'll put in a fix.

**Comment by jleidel** [comment]
confirmed fix; closing
