### ISSUE TITLE
sst-info broken in new split-core

### ISSUE THREAD

**Issue by bjmoor** [sstsimulator/sst-core#83]
Reported by a customer:

> -> sst-info miranda
> ERROR: No such file or directory - When trying to open Directory @SST_ELEMLIB_DIR@
> PROCESSED 0 .so (SST ELEMENT) FILES FOUND IN DIRECTORY @SST_ELEMLIB_DIR@

Looks like sst-info doesn't pull the search path from the SST configuration, but rather the hard-coded #define.

**Comment by allevin** [comment]
Duplicate of #78

**Comment by bjmoor** [comment]
Closing, as duplicate of #78
