### ISSUE TITLE
Catch HDF5 exceptions by const ref

### ISSUE THREAD

**Issue by pdbj** [sstsimulator/sst-core#837]
HDF5 exceptions are polymorphic, must be caught by ref not value.

Patch [Catch exception by const ref](https://github.com/pdbj/sst-core/commit/00716437f19ac9cd152b6c78dff5fdcc1be01e74)

**Comment by pdbj** [comment]
Rebased [Catch exception by const ref](https://github.com/pdbj/sst-core/commit/e3dbc8ee54830ddcc8929e59b670c290a63bbe51)

**Comment by pdbj** [comment]
Has this been merged yet?

**Comment by feldergast** [comment]
I thought we had added it to another PR, but I'm not seeing the changes in devel or master.  We'll need to do a separate PR for it.
