### ISSUE TITLE
getTimeLord deprecation warning

### ISSUE THREAD

**Issue by kemstevens** [sstsimulator/sst-core#860]
Hello,
I note that under SST 12 if your code called getTimeLord() from SST::Simulation, there is now a deprecation warning.  Unfortunately, the warning is not very clear about what to call instead.  Based on the message, I tried to grep the sst core course code for an alternative getTimeLord() function but found nothing.  What is the recommended replacement for this function going forward?

**Comment by gunney1** [comment]
I'm also interested in this issue.  I use the TimeLord to get the TimeConverter used by the Simulator.  I see that it has moved to Simulator_impl, but there's not public access to that class.

**Comment by feldergast** [comment]
BaseComponent::getCoreTimeBase() will give you the timebase used by the Simulation object.  If you need a TimeConverter, you can then call BaseComponent::getTimeConverter() to create a TimeConverter from it (by definition, it will have a factor of 1).  If you’re trying to get these from a class inheriting from a different core class, let me know what class.  We are getting rid of the static functions to allow greater flexibility in parallelization in the future.  All access to time elements in the core will have to go through other classes that the models inherit from.  The time functions are part of the public const BaseComponent API, so you can also access the time functions through a pointer to a Component or BaseComponent.

**Comment by feldergast** [comment]
Are these BaseComponent API calls sufficient for you use cases?  If so, can I close this issue?

**Comment by gunney1** [comment]
Yes, they're sufficient.  Thank you.

**Comment by ritheshn** [comment]
Currently, there is not any deprecation warning for calling getTimeLord(), and the required functionality exists within BaseComponent (by utilizing the simulation_impl.h file). The simulation.h file indicates that it will be removed by SST 14. I spoke to kemstevens and she is satisfied with the update, so we are good to close this issue.

**Comment by feldergast** [comment]
Just to be clear, the simulation_impl.h file will not be available outside of the core starting with SST 14.  Do you still have the functionality you need from the BaseComponent API?  Want to make sure you have the functionality you need when SST 14 drops.

**Comment by ritheshn** [comment]
Yes, the BaseComponent API sufficiently contains the desired functionality

**Comment by feldergast** [comment]
Thanks.  Closing.
