### ISSUE TITLE
Integration with Dakota

### ISSUE THREAD

**Issue by debjyoti0891** [sstsimulator/sst-core#863]
One of the early SST tutorials mention Dakota (https://dakota.sandia.gov/quickstart.html) for DSE to enable hardware-software codesign. Is there any code /example that shows how SST can be interfaced with Dakota?

**Comment by berquist** [comment]
I can't find any examples our website tutorials that mention Dakota, but there are almost certainly no extant examples.  There's no mention of SST in https://github.com/snl-dakota/dakota either.
