### ISSUE TITLE
Can SST be configured with OpenMPI that has UCX disabled or configured with alternative?

### ISSUE THREAD

**Issue by rachelwaldon** [sstsimulator/sst-core#869]
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement
I'm trying to build SST-Core version 12.0.0 inside a podman container. I get this error when I run $ sst --version inside the container

![podman3](https://user-images.githubusercontent.com/42785514/182723937-35120eb1-8451-4563-8d62-ce357c9de6b3.PNG)

Basically I have an issue where UCX is trying to access a file that podman does not expose for a rootless container. Are there any alternatives to UCX for OpenMPI that are known to work with SST?

2 - Describe how to reproduce the issue

      1. Built podman image with podman for Windows with a Dockerfile that installs SST Core and dependencies
      2. Run podman container and the error described above is thrown for running sst.
      
3 - What Operating system(s) and versions 

      The podman container was built on Windows 10, wsl2.
        SST Core version 12.0.0 running on rockylinux 8.5 inside the container.

4 - What version of external libraries (Boost, MPI)

      Open MPI 4.1.1

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by jleidel** [comment]
@rachelwaldon, we have a number of OpenMPI builds (including 4.1.0) that do not utilize UCX.

**Comment by rachelwaldon** [comment]
Great news thanks, where could I find that or how can I build that? I have tried compiling openmpi with configure flags --without-ucx and --without-hcol and I got errors.
![error](https://user-images.githubusercontent.com/42785514/184071252-27f44a3a-7b18-47fc-ba33-e3e60146386c.PNG)

**Comment by jleidel** [comment]
Our environment is rather simple with respect to OpenMPI.  We use `--prefix=/path/to/install --with-slurm` as our configuration lines.  We simply do not enable UCX by default.  Also keep in mind that we link against the Slurm batch scheduling system.  

From the looks of your console, you appear to be running within a container of some sort.  A few things:
- OpenMPI generally frowns upon running as root.  This sometimes produces strange behavior.
- If you are running with a container, we've experienced issues whereby the multitude of containers and/or the host system do not have the same version of MPI.  EG, if your container host has MPI installed, the parallel job may be resolving paths (and subsequently libraries) from both the host environment and the container environment.   If this is the case, I would suggest taking a look at some documentation and/or container configs (Singularity) listed below.  

https://github.com/sstsimulator/sst-documentation/blob/devel/Tutorials/Containers.md
https://github.com/tactcomplabs/sst-containers/

**Comment by rachelwaldon** [comment]
Thanks for the help. Yeah I was just wondering if you use different network libraries to see if I could use a different one than UCX, but I think for now I may just try to suppress the warning it seems UCX is recommended for newer versions of openmpi. 

Yes I'm trying to containerize SST into a podman container. Yes I'm running it as a fakeroot inside the container. I looked at your SST Dockerfiles where you add a linux user. So should I add a linux user to my Dockerfile in podman even in rootless mode? I mean best practice is least privilege as possible right?
