### ISSUE TITLE
Responses with F_FAIL are reported as successful

### ISSUE THREAD

**Issue by PhilippKasgen** [sstsimulator/sst-core#886]
https://github.com/sstsimulator/sst-core/blob/41d2df9e53505f19ddb117a1ff32190f9ef2010e/src/sst/core/interfaces/stdMem.h#L160

When the `F_FAIL` flag is set, `getSuccess()` will report true, since the `~` operator inverts bit-wise. A fix for this could be:

```
bool getSuccess() { return (flags & static_cast<int>(Flag::F_FAIL)) == 0; }
```

**Comment by gvoskuilen** [comment]
Closing since it has been fixed.
