### ISSUE TITLE
Trac: #275 Upon successful nightly build TITLE test, publish make dist tarball and svn rev num

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#9]
This ticket collects two related enhancements. Developers are often unsure when to do an svn update in their sandbox. They dont really know if the head of the trunk produced a good build or not. We need to publish in some *very convenient* place the svn revision number that was used for the last successfull build *and* test of the trunk during the nightly process. In a similar vein, some non-developer users may need a version of the source code from the trunk in order to obtain a new feature or bug fix. They too are at risk if they simply check out the trunk head. Instead, provide a tarball of the last successful build *and* test of the trunk during the nightly process.

**Comment by allevin** [comment]
Moved to sst-sqe
