### ISSUE TITLE
how to use pytest-mpi with sst

### ISSUE THREAD

**Issue by rachelwaldon** [sstsimulator/sst-core#908]
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement
I am trying to use pytest-mpi for testing test cases with sst simulations. The typical ways I have tried calling pytest don't seem to work. 

2 - Describe how to reproduce the issue
If I use sst as a python interpreter I get this error:

![image](https://user-images.githubusercontent.com/42785514/217070609-935c7804-17ac-49a9-b69c-5a1fbb45594e.png)

When I try to invoke pytest from python code I get a fork error:

![image](https://user-images.githubusercontent.com/42785514/217072228-846f7835-0f42-4782-b8a7-8f4091a0835f.png)

![image](https://user-images.githubusercontent.com/42785514/217072537-df901297-503b-47a8-abbf-538324315038.png)

3 - What Operating system(s) and versions 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"

4 - What version of external libraries (Boost, MPI)
openmpi 4.1.0

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)
sst 12.1.0

6 - Fill out Labels, Milestones, and Assignee fields as best possible

**Comment by feldergast** [comment]
I don't have any experience with pytest, but a quick look at the website would suggest that it will not work inside of sst.  While sst uses a python interpreter to parse input files, it has the very specific purpose of creating a ConfigGraph object that can be used by sst to build the simulation.  Test frameworks like pytest are not going to work within those constraints.

**Comment by rachelwaldon** [comment]
Hmmm... okay. I was reading here https://pytest-mpi.readthedocs.io/en/latest/usage.html that pytest can be used to run under mpi. Why specifically can't it work with sst? Let's take sst command out of it and say I made a graph simulation with ahp_graph instead and invoked the simulation with python3 like here https://github.com/lpsmodsimteam/ahp_graph/tree/master/examples/pingpong

then I could call: $ mpirun -n 2 python3 -m pytest <inputfile>

Would that work? If not, I feel pytest is a pretty standard framework, do you have suggestions for other python testing frameworks that work with sst? Thanks for any help.

**Comment by feldergast** [comment]
Let's back up a bit. What exactly are you trying to accomplish?  SST uses a framework based on unittest to do our testing, but the framework is run outside of SST and invokes sst with various input files and checks the output.  I'm not understanding why you want to run pytest inside of SST.  I suspect you could use pytest in a similar fashion.

Also, SST is definitely not a substitute for a python interpreter and can't be used interchangeably with one.

**Comment by rachelwaldon** [comment]
Thanks, my goal is to run a lot of parallel simulations of sst with slight variations like a regression testing test suite. I want to use pytest to run a group of parallel tests from the command line. Yes thanks for clarifying I now understand sst can't be used like a python interpreter I will try  with ahp_graph. Can you please point me to an example of how you set up your unittest framework, is it public in the repo somewhere? Thanks.

**Comment by feldergast** [comment]
The framework code is in the core repo under sst/core/testingFramework and the testing files that use it are in sst/tests in the core repo.  In the elements repo, each element has a tests subdirectory that has their test scripts that use the framework.

**Comment by rachelwaldon** [comment]
Great thanks!
