### ISSUE TITLE
Compilation Error -- error: ‘event_dump_file_’ was not declared in this scope

### ISSUE THREAD

**Issue by hughes-c** [sstsimulator/sst-core#914]
sst-core will not compile if --disable-mem-pools is set.
devel [219a6b19](https://github.com/sstsimulator/sst-core/commit/219a6b198a209c3e5d7e0c1e10bf55bcd7508fe5)

`In file included from ../../../src/sst/core/heartbeat.h:16,
                 from heartbeat.cc:14:
../../../src/sst/core/config.h: In member function ‘virtual void SST::Config::serialize_order(SST::Core::Serialization::serializer&)’:
../../../src/sst/core/config.h:382:14: error: ‘event_dump_file_’ was not declared in this scope
  382 |         ser& event_dump_file_;
`

**Comment by William-An** [comment]
Looks like `event_dump_file_` is excluded when compiling with mem pools disable [here](https://github.com/sstsimulator/sst-core/blob/912715f401a4cdde49f17e4212484a53617516e3/src/sst/core/config.h#L461-L463):

```
#ifdef USE_MEMPOOL
    std::string event_dump_file_; /*!< File to dump undeleted events to */
#endif
```
