### ISSUE TITLE
CMake Build Infrastructure Broken: Requires CXX17 Support

### ISSUE THREAD

**Issue by jleidel** [sstsimulator/sst-core#922]
The experimental CMake support in SST-Core (master) as of 03/09/23 is broken due to the recent move to support CXX17.  This should be an easy fix.

Trace Snippet:
```
/usr/include/c++/7/atomic:668:7: note: declared here
       atomic(const atomic&) = delete;
       ^~~~~~
/usr/include/c++/7/atomic:672:17: note:   after user-defined conversion: constexpr std::atomic<int>::atomic(std::atomic<int>::__integral_type)
       constexpr atomic(__integral_type __i) noexcept : __base_type(__i) { }
```

**Comment by gvoskuilen** [comment]
@jleidel @feldergast Is this fixed with the latest cmake update?

**Comment by jleidel** [comment]
@gvoskuilen, this passes all the TCL/SST CMake tests.  I'm good to close
