### ISSUE TITLE
link to doxygen documentation from sst-simulator.org

### ISSUE THREAD

**Issue by researcherben** [sstsimulator/sst-core#926]
Currently the page <https://sst-simulator.org/> links "Documentation" to the URL <https://sst-simulator.org/sst-docs/>, and that page has, among other links, links to `sst-core` and `sst-elements`.

I wasn't able to find a link to <https://sst-simulator.org/SSTDoxygen/Latest/html/>

The searchbar on <https://sst-simulator.org/> doesn't return relevant pages for Doxygen output. 

(On a related note, the page <https://sst-simulator.org/SSTPages/SSTDeveloperSSTdoxygenQuickStart/> links to the text "doxygen commands" at the bottom to an invalid URL, <https://www.stack.nl/~dimitri/doxygen/manual/commands.html>. The relevant URL is <https://www.doxygen.nl/index.html>.)

**Comment by gvoskuilen** [comment]
SSTDoxygen is separate from sst-docs and is linked to particular releases. There is a link to it on sst-simulator.org -> Releases -> Core Documentation. Elements doesn't have doxygen. "Latest" is a symlink to the documentation from the most recent release, currently v12.1.0. I can look into why search on sst-simulator.org doesn't return doxygen, it may just be searching SSTPages/.

I did update the invalid URL, thanks for locating that.

**Comment by researcherben** [comment]
Thank you
