### ISSUE TITLE
OpenMPI MacPorts Install isn't in Documentation

### ISSUE THREAD

**Issue by nmhamster** [sstsimulator/sst-core#94]
@mjleven was performing a new install with MacPorts and OpenMPI is not listed in the how-to. We should probably add this.

**Comment by bjmoor** [comment]
I see OpenMPI all over the documentation at the moment.  Has this already been addressed?    Also, the documentation says that OpenMPI is a requirement.  It is not.

**Comment by allevin** [comment]
Existing documentation was modified to add additional information on clang version of openmpi (gcc 48 version was already documented).  

see http://sst-simulator.org/SSTPages/SSTUserBuildAndInstallSSTOnMacOSXUsingMacPorts/

Users can search for information on the website on the "search" field on the bottom of the left links bar.
