### ISSUE TITLE
Out-of-date Spack packages for sst-core and sst-elements

### ISSUE THREAD

**Issue by naromero77** [sstsimulator/sst-core#948]
Hi,

I was installing the sst-core and sst-elements via Spack. I noticed the packages had not been updated in a way.

Is there any interest among the developers in keeping it updated? Also, I think what is in Spack doesn't seem to install/set-up the Python modules correctly.

I can certainly try to do a PR into Spack with an updated package, but some projects prefer to do it themselves.

Thanks for your consideration.

**Comment by berquist** [comment]
Apologies for the long delay in updating.  It's been added back to our release procedure and I'll make Spack PRs to update all the packages.  I might need you to be a guinea pig during development, since the matrix of combinations between core/elements/macro is large.

**Comment by naromero77** [comment]
I am happy to be a guinea pig. You can also add me as a reviewer (naromero77).

Even though its sst-* are mostly C++ packages, because of the Python bits. You will need to do something like this to make sure the Python runtime environment is set-up correctly for each of the sst-* packages.
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/qmcpack/package.py#L410-L415
(just the PYTHONPATH parts)

**Comment by naromero77** [comment]
It looks like SST calls the Python interpreter from C++. I think what needs to happen is that LD_LIBRARY_PATH for libpython.so needs to get added into the Spack runtime environment.

**Comment by berquist** [comment]
I have updated versions for `core`, `elements`, `macro`, and `dumpi`, and was trying to write tests for `core` (triggering `sst-test-core` after build but before install), but I might leave those out until I better understand testing packages in Spack.

My question is that without changing anything other than the versions, I wasn't seeing problems running `sst config.py` where `config.py` is any of the `core` test files.  This is because I was using them in a Spack environment.  How are you trying to run core?

**Comment by naromero77** [comment]
The other thing that I cannot get working after a `spack load sst-elements`
```
sst-test-elements -w "*Ariel"
```

One problem is that the tests do not get installed, but even if I try to put to a point to a particular test directory by doing:
```
sst-test-elements -p /sal/home/n.a.romero/archive/sst-elements-library-13.0.0/src -w "*Ariel"
```

I get an odd error message:
```
INFO: SST Test Engine Instantiated - Running tests on Registered Elements
INFO: Test Platform = UBUNTU 20.04
INFO: Running on Python Version = 3.10.10
INFO: TestEngine Version = (13.0.0)
INFO: Available Cores = 64; Num Ranks = 1; Num Threads = 1
INFO: TestSuite wildcards to search for: testsuite_*Ariel.py
INFO: Test scenarios to filter tests: NONE
INFO: SST Test Output Directory = /sal/home/n.a.romero/sst-tutorials/exercises/ex4/sst_test_outputs
FATAL: SST-Elements Directory /tmp/n.a.romero/spack-stage/spack-stage-sst-elements-13.0.0-qmuhd25tjohhotgt5nfyqtneilr4fhqf/spack-src/spack-build/src/ - Does not exist - testing cannot continue
```

It is looking for an **old** Spack stage directory that is gone. Possibly due to the contents of:
```
sst-core-<version>/etc/sst/sstsimulator.conf
```
which contains a number of Spack stage directories that have been removed by Spack.

**Comment by berquist** [comment]
I haven't encountered the first problem (I don't think...) but am definitely encountering the second and third.  I am not against you making the Spack PR, I just wanted to understand the issues better first, and now I do.

If you make the PR into Spack, then I can make PRs into your branch.

**Comment by berquist** [comment]
Spack PR: https://github.com/spack/spack/pull/37467

I can't add you as a reviewer via the interface but you should still be able to provide a review.

I thought I had the env activated, but now I see that too:
```
/tmp/sst
[eric@osmium]$ command -v python
/home/eric/data/spack/var/spack/environments/sst-elements-pin-dev/.spack-env/view/bin/python
/tmp/sst
[eric@osmium]$ realpath $(command -v python)
/home/eric/data/spack/var/spack/environments/sst-elements-pin-dev/.spack-env/._view/j6vwamdv7p2fjk3smybl3hlwnjtuwqar/bin/python3.10
/tmp/sst
[eric@osmium]$ file $(realpath $(command -v python))
/home/eric/data/spack/var/spack/environments/sst-elements-pin-dev/.spack-env/._view/j6vwamdv7p2fjk3smybl3hlwnjtuwqar/bin/python3.10: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=2716f5b0bf24bf3d0db6fb0d84bccfe4b845dfaf, for GNU/Linux 4.4.0, with debug_info, not stripped
/tmp/sst
[eric@osmium]$ sst /tmp/eric/spack-stage/spack-stage-sst-elements-13.0.0-obvox46eeqolwd7lu5lz6sbrd3irtrw3/spack-src/src/sst/elements/shogun/tests/hierarchy_test.py
sst: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
/tmp/sst
[eric@osmium]$ sst /tmp/sst/sst-core-13.0.0_Final/tests/test_PythonUnitAlgebra.py
sst: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
/tmp/sst
[eric@osmium]$ command -v sst
/home/eric/data/spack/var/spack/environments/sst-elements-pin-dev/.spack-env/view/bin/sst
/tmp/sst
[eric@osmium]$ ldd $(command -v sst)
        linux-vdso.so.1 (0x00007ffd825e7000)
        libmpi.so.40 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/openmpi-4.1.5-ofoeeqiirlsyerba23bgzytsrfqhcj5r/lib/libmpi.so.40 (0x00007fcf98a00000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fcf98600000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fcf98dcc000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fcf98da7000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fcf98416000)
        libopen-rte.so.40 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/openmpi-4.1.5-ofoeeqiirlsyerba23bgzytsrfqhcj5r/lib/libopen-rte.so.40 (0x00007fcf988dc000)
        libopen-pal.so.40 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/openmpi-4.1.5-ofoeeqiirlsyerba23bgzytsrfqhcj5r/lib/libopen-pal.so.40 (0x00007fcf98311000)
        libpmix.so.2 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/pmix-4.1.2-tlhc54thmxmxdlobw3yaddkmi3wyxbz7/lib/libpmix.so.2 (0x00007fcf98112000)
        libnl-3.so.200 => /usr/lib/libnl-3.so.200 (0x00007fcf98d81000)
        libnl-route-3.so.200 => /usr/lib/libnl-route-3.so.200 (0x00007fcf98083000)
        libz.so.1 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/zlib-1.2.13-3r5g7zlu6z7ivqy4a63dh75mvxm5darg/lib/libz.so.1 (0x00007fcf98d65000)
        libhwloc.so.15 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/hwloc-2.9.0-3nclmcbk5izxavhis4yqwpiihspbqeij/lib/libhwloc.so.15 (0x00007fcf9887c000)
        libevent_core-2.1.so.7 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/libevent-2.1.12-ykiphgiuz7gzb7546narkekw34lmwbin/lib/libevent_core-2.1.so.7 (0x00007fcf98d2e000)
        libevent_pthreads-2.1.so.7 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/libevent-2.1.12-ykiphgiuz7gzb7546narkekw34lmwbin/lib/libevent_pthreads-2.1.so.7 (0x00007fcf98d29000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fcf98f18000)
        libpciaccess.so.0 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/libpciaccess-0.16-k4fndrmnmtmfxlm4mrx22hi3kiqsf4od/lib/libpciaccess.so.0 (0x00007fcf98d1b000)
        libxml2.so.2 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/libxml2-2.10.3-6mhdntgjuqyaicy3siwcmtcbs5qz75g2/lib/libxml2.so.2 (0x00007fcf97f17000)
        liblzma.so.5 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/xz-5.4.1-75lax4mmh5cqyw363hbmkuce74k5hx53/lib/liblzma.so.5 (0x00007fcf97ee9000)
        libiconv.so.2 => /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/libiconv-1.17-n4xxfejmfxupstykqp62r7nvuh76o3bx/lib/libiconv.so.2 (0x00007fcf97dda000)
```

**Comment by naromero77** [comment]
Yep, that's what I saw too. This bit of code in `sst-core.py` should fix it for you:
```
    def setup_run_environment(self, env):
        """Set-up runtime environment for SST Core."""

        env.prepend_path("LD_LIBRARY_PATH", self.spec["python"].prefix.lib)
```

**Comment by naromero77** [comment]
> Trying to build by hand using `--with-python=/home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf`, the shell environment not being modified by `spack load` or any other method, and already encountering something:
> 
> ```
> checking for python3-config... /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf/bin/python3-config
> checking python-config exists... /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf/bin/python3-config
> checking for python3... /home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf/bin/python3
> configure: Python version is Python 3.10.10
> checking for Python.h... yes
> checking for Py_Initialize in -lpython3.10... no
> checking for Py_Initialize in -lpython3.10... no
> checking for Py_Initialize in -lpython3.10... no
> checking python libraries... no
> configure: error: Unable to locate Python library python3.10 in  -L/home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf/lib -lpython3.10 -lcrypt -lintl -ldl  -lm -lm   -L/home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf/lib -L/home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-9.4.0/python-3.10.10-nmi6agvyufilxgi5l66qkl2qhyqnnewf/lib64
> ```

Does `--with-python=<path>` set the value of `PYTHONHOME`?
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME

You might try just setting it manually before you run configure and see if the behavior is any different.

**Comment by feldergast** [comment]
> 1. I've confirmed that modifying `LD_LIBRARY_PATH` does fix this problem with `sst`, but am trying to find the root cause, mostly because I think this is a SST issue and not a Spack one.  The `ldd sst` output is not helpful in saying the link problem is with both `libexec/sstinfo.x` and `libexec/sstsim.x`, not the `sst` binary itself.  I'll spend another day or two investigating, and if I can't figure it out, I'll put the runtime `LD_LIBRARY_PATH` modification into the Spack package file.

The sst executable does not actually link in any of the python libraries.  It is just a wrapper/bootloader for the sstsim.x executable (similarly, sst-info is just a wrapper for sstinfo.x).  The bootloader executables configure the environment according to what's in the sstsimulator.conf file.  This was done because most of the bugs coming back were happening because the environment that the code was built in was different from the one the user ran with.  The bootloader makes sure they are the same.  I'm not sure why sst would run without Python in the LD_LIBRARY_PATH outside of spack and would need it when loaded through Spack.  The bootloader does rewrite the LD_LIBRARY_PATH before invoking sstsim.x, but it does include the base LD_LIBARRY_PATH in the new path (it is the last thing in the new path).

**Comment by berquist** [comment]
Before going into more technical details, another workaround is to build a static `libpython` (`spack add/install python~shared`).

---

This is not a Spack-specific problem, but Spack triggers it.  `ldd` reveals the library is not available not only because it isn't on `LD_LIBRARY_PATH`, but it isn't set in its `RPATH` or `RUNPATH` either.  Here is an example of a "successful" build against system Python (Spack is only used for the compiler):
```
$ ldd sst-core-build/src/sst/core/sstsim.x
<snip>
        libpython3.11.so.1.0 => /usr/lib/libpython3.11.so.1.0 (0x00007fc9bee00000)
<snip>
$ readelf -d sst-core-build/src/sst/core/sstsim.x

Dynamic section at offset 0x2a3d58 contains 35 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libpython3.11.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_cpp.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_cxx.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/gcc-9.4.0-djkn6aazq2h3f47ogglypa43nb6yyaf4/lib64:/usr/lib]
<snip>
```
All the other `NEEDED` libraries are in either the compiler or system library directories.  `RPATH` isn't present because it isn't set.  When linking against an external Python's shared library, Spack or otherwise, the installed SST binaries from both autotools and CMake have the correct `NEEDED` library version, but the additional library directory is not added by the linker.  Interestingly, the built binaries from CMake have the correct `RUNPATH` which is then stripped during installation.  There are CMake variables that control this behavior.  autotools doesn't have a trivial way of changing this.

The Spack-only solution is to switch it from an autotools build to a CMake one and patch the CMake to not strip this path on installation.  I don't like the idea of forcing the use of a statically-built Python.

Bedtime reading about dynamic library lookup on these paths:
- https://www.qt.io/blog/2011/10/28/rpath-and-runpath
- https://stackoverflow.com/questions/2836330/is-there-a-programmatic-way-to-inspect-the-current-rpath-on-linux
- https://stackoverflow.com/a/16922836

> Trying to build by hand (...)

This is a problem with `gettext` on my machine from the distribution package manager vs. as a Spack Python dependency and not actually related to how SST depends on Python, so not particularly relevant.

**Comment by naromero77** [comment]
> Before going into more technical details, another workaround is to build a static `libpython` (`spack add/install python~shared`).

I would stay away from a statically built Python. I did that once for a code that is design similar to SST and it caused other unintended side-effects that were not easy to mitigate.

> 
> This is not a Spack-specific problem, but Spack triggers it. `ldd` reveals the library is not available not only because it isn't on `LD_LIBRARY_PATH`, but it isn't set in its `RPATH` or `RUNPATH` either. Here is an example of a "successful" build against system Python (Spack is only used for the compiler):
> 
> ```
> $ ldd sst-core-build/src/sst/core/sstsim.x
> <snip>
>         libpython3.11.so.1.0 => /usr/lib/libpython3.11.so.1.0 (0x00007fc9bee00000)
> <snip>
> $ readelf -d sst-core-build/src/sst/core/sstsim.x
> 
> Dynamic section at offset 0x2a3d58 contains 35 entries:
>   Tag        Type                         Name/Value
>  0x0000000000000001 (NEEDED)             Shared library: [libpython3.11.so.1.0]
>  0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libhdf5.so.310]
>  0x0000000000000001 (NEEDED)             Shared library: [libhdf5_cpp.so.310]
>  0x0000000000000001 (NEEDED)             Shared library: [libmpi_cxx.so.40]
>  0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.40]
>  0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
>  0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
>  0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
>  0x000000000000001d (RUNPATH)            Library runpath: [/home/eric/data/spack/opt/spack/linux-archrolling-zen/gcc-12.2.1/gcc-9.4.0-djkn6aazq2h3f47ogglypa43nb6yyaf4/lib64:/usr/lib]
> <snip>
> ```
> 
> All the other `NEEDED` libraries are in either the compiler or system library directories. `RPATH` isn't present because it isn't set. When linking against an external Python's shared library, Spack or otherwise, the installed SST binaries from both autotools and CMake have the correct `NEEDED` library version, but the additional library directory is not added by the linker. Interestingly, the built binaries from CMake have the correct `RUNPATH` which is then stripped during installation. There are CMake variables that control this behavior. autotools doesn't have a trivial way of changing this.
> 
> The Spack-only solution is to switch it from an autotools build to a CMake one and patch the CMake to not strip this path on installation. I don't like the idea of forcing the use of a statically-built Python.
> 
> Bedtime reading about dynamic library lookup on these paths:
> 
> * https://www.qt.io/blog/2011/10/28/rpath-and-runpath
> * https://stackoverflow.com/questions/2836330/is-there-a-programmatic-way-to-inspect-the-current-rpath-on-linux
> * https://stackoverflow.com/a/16922836
> 
> > Trying to build by hand (...)
> 
> This is a problem with `gettext` on my machine from the distribution package manager vs. as a Spack Python dependency and not actually related to how SST depends on Python, so not particularly relevant.

I think that I understand, but I am going to need to read this carefully :) Thanks for the detailed explanation.

I haven't studied the design of SST core but it looks like `sst` is just a thing wrapper around `sstsim.x` and that the PYTHON directory gets stripped out of RPATH for `sstsim.x` by autotools. (I didn't even realize that SST had a CMake build system).

**Comment by berquist** [comment]
@naromero77 Please try the Spack build again, I think it's finally ready.

**Comment by berquist** [comment]
Fixed by https://github.com/spack/spack/pull/37467.
