### ISSUE TITLE
about simulated time

### ISSUE THREAD

**Issue by chaojibendan** [sstsimulator/sst-core#959]
When I try to run a more complex program, such as a loop of one million iterations, using the Ariel processor, it takes one minute to execute. However, the displayed simulation time shows only 90 milliseconds (I have disabled data statistics). I don't know why.

**Comment by chaojibendan** [comment]
Is there a way to execute the program only？ sometimes i just want to test if the program can run.

**Comment by berquist** [comment]
The same as https://github.com/sstsimulator/sst-elements/issues/2157.  @hughes-c I think they are asking if there is a static way to find if their sim is valid without executing it.

**Comment by chaojibendan** [comment]
Thank you very much. I try the way that just change hz and it's effective. I'm just confused with the long running time. Maybe the time is necessary.
